'//////////////////////////////////////////////////////////////
'// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
'//////////////////////////////////////////////////////////////
'// Code is generated on: 
'// Code is generated using templates: SD.TemplateBindings.SharedTemplates
'// Templates vendor: Solutions Design.
'//////////////////////////////////////////////////////////////
Imports System
Imports System.Linq
Imports System.Collections.Generic
Imports SD.LLBLGen.Pro.LinqSupportClasses
Imports SD.LLBLGen.Pro.ORMSupportClasses
Imports DAL.EntityClasses
Imports DAL.FactoryClasses

Namespace DAL.Linq
	''' <summary>Meta-data Class For the construction of Linq queries which are To be executed using LLBLGen Pro code.</summary>
	Public Class LinqMetaData
		Implements ILinqMetaData
		
		''' <summary>CTor. Using this ctor will leave the IDataAccessAdapter Object To use empty. To be able To execute the query, an IDataAccessAdapter instance
		''' Is required, And has To be Set On the LLBLGenProProvider2 Object In the query To execute. </summary>
		Public Sub New()
			Me.New(Nothing, Nothing)
		End Sub
		
		''' <summary>CTor which accepts an IDataAccessAdapter implementing Object, which will be used To execute queries created With this metadata Class.</summary>
		''' <param name="adapterToUse">the IDataAccessAdapter To use In queries created With this meta data</param>
		''' <remarks> Be aware that the IDataAccessAdapter Object Set via this Property Is kept alive by the LLBLGenProQuery objects created With this meta data till they go out of scope.</remarks>
		Public Sub New(adapterToUse As IDataAccessAdapter)
			Me.New(adapterToUse, Nothing)
		End Sub

		''' <summary>CTor which accepts an IDataAccessAdapter implementing Object, which will be used To execute queries created With this metadata Class.</summary>
		''' <param name="adapterToUse">the IDataAccessAdapter To use In queries created With this meta data</param>
		''' <param name="customFunctionMappings">The custom Function mappings To use. These take higher precedence than the ones In the DQE To use.</param>
		''' <remarks> Be aware that the IDataAccessAdapter Object Set via this Property Is kept alive by the LLBLGenProQuery objects created With this meta data till they go out of scope.</remarks>
		Public Sub New(adapterToUse As IDataAccessAdapter, customFunctionMappings As FunctionMappingStore)
			Me.adapterToUse = adapterToUse
			Me.CustomFunctionMappings = customFunctionMappings
		End Sub
		
		''' <summary>returns the datasource To use In a Linq query For the entity type specified</summary>
		''' <param name="typeOfEntity">the type of the entity To Get the datasource For</param>
		''' <returns>the requested datasource</returns>
		Public Function GetQueryableForEntity(typeOfEntity As Integer) As IDataSource Implements ILinqMetaData.GetQueryableForEntity
			Select Case CType(typeOfEntity, DAL.EntityType)
				Case DAL.EntityType.AttivitaEntity
					Return Me.Attivita
				Case DAL.EntityType.AttrezzaturaAttivitaEntity
					Return Me.AttrezzaturaAttivita
				Case DAL.EntityType.AuditEntity
					Return Me.Audit
				Case DAL.EntityType.AziendaEntity
					Return Me.Azienda
				Case DAL.EntityType.AziendaProdottoEntity
					Return Me.AziendaProdotto
				Case DAL.EntityType.ComuneEntity
					Return Me.Comune
				Case DAL.EntityType.ContattoEntity
					Return Me.Contatto
				Case DAL.EntityType.DichiarazioneEntity
					Return Me.Dichiarazione
				Case DAL.EntityType.DichiarazioneOnLineEntity
					Return Me.DichiarazioneOnLine
				Case DAL.EntityType.EventoAziendaEntity
					Return Me.EventoAzienda
				Case DAL.EntityType.IncassoEntity
					Return Me.Incasso
				Case DAL.EntityType.LicenzaAziendaEntity
					Return Me.LicenzaAzienda
				Case DAL.EntityType.MaterialeEntity
					Return Me.Materiale
				Case DAL.EntityType.MaterialeQuadroEntity
					Return Me.MaterialeQuadro
				Case DAL.EntityType.ParametroEntity
					Return Me.Parametro
				Case DAL.EntityType.ProdottoEntity
					Return Me.Prodotto
				Case DAL.EntityType.ProdottoDichiaratoEntity
					Return Me.ProdottoDichiarato
				Case DAL.EntityType.ProvinciaEntity
					Return Me.Provincia
				Case DAL.EntityType.QuadroEntity
					Return Me.Quadro
				Case DAL.EntityType.RegioneEntity
					Return Me.Regione
				Case DAL.EntityType.RigaDichiarazioneEntity
					Return Me.RigaDichiarazione
				Case DAL.EntityType.RiunioneEntity
					Return Me.Riunione
				Case DAL.EntityType.RuoloUtenteEntity
					Return Me.RuoloUtente
				Case DAL.EntityType.ScadenzaEntity
					Return Me.Scadenza
				Case DAL.EntityType.SedeEntity
					Return Me.Sede
				Case DAL.EntityType.UtenteEntity
					Return Me.Utente
				Case DAL.EntityType.AllegatoEntity
					Return Me.Allegato
				Case DAL.EntityType.AziendaAllegatoEntity
					Return Me.AziendaAllegato
				Case DAL.EntityType.CodiciCerEntity
					Return Me.CodiciCer
				Case DAL.EntityType.DettaglioAllegatoEntity
					Return Me.DettaglioAllegato
				Case DAL.EntityType.AliquotaIvaEntity
					Return Me.AliquotaIva
				Case DAL.EntityType.CategoriaEntity
					Return Me.Categoria
				Case DAL.EntityType.EventoEntity
					Return Me.Evento
				Case DAL.EntityType.FormaGiuridicaEntity
					Return Me.FormaGiuridica
				Case DAL.EntityType.InfoStatoEntity
					Return Me.InfoStato
				Case DAL.EntityType.ModalitaPagamentoEntity
					Return Me.ModalitaPagamento
				Case DAL.EntityType.QuotaAdesioneEntity
					Return Me.QuotaAdesione
				Case DAL.EntityType.RuoloContattoEntity
					Return Me.RuoloContatto
				Case DAL.EntityType.StatoSocioEntity
					Return Me.StatoSocio
				Case DAL.EntityType.TipoAttivitaEntity
					Return Me.TipoAttivita
				Case DAL.EntityType.TipoAttrezzaturaEntity
					Return Me.TipoAttrezzatura
				Case DAL.EntityType.TipoLicenzaEntity
					Return Me.TipoLicenza
				Case DAL.EntityType.TipoMaterialeEntity
					Return Me.TipoMateriale
				Case DAL.EntityType.TipoQuadroEntity
					Return Me.TipoQuadro
				Case DAL.EntityType.TipoSedeEntity
					Return Me.TipoSede
				Case DAL.EntityType.TipoSocioEntity
					Return Me.TipoSocio
				Case DAL.EntityType.TitoloContattoEntity
					Return Me.TitoloContatto
				Case DAL.EntityType.UnitaMisuraEntity
					Return Me.UnitaMisura
				Case Else
					Return Nothing
			End Select

		End Function

		''' <summary>returns the datasource to use in a Linq query which wraps the specified SQL query and projects it to instances of type T</summary>
		''' <param name="sqlQuery">The SQL query to execute. Has to follow one of the parameter specification patterns for Plain SQL queries in the LLBLGen Pro Runtime Framework</param>
		''' <param name="parameterValues">The object which will provide the parameter values for the SQL query specified. Has to follow one of the parameter specification patterns for Plain SQL queries in the LLBLGen Pro Runtime Framework</param>
		''' <typeparam name="T">The type of the instances to project the rows into, returned by the SQL query specified</typeparam>
		''' <returns>the requested datasource</returns>
		<InMemoryCandidate()> _		
		Public Function FromSql(Of T As Class)(sqlQuery as String, parameterValues as Object) As DataSource2(Of T)
			Return New DataSource2(Of T)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse).SetWrappedPlainSQLQuerySpecification(sqlQuery, parameterValues)
		End Function

		''' <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		''' <typeparam name="TEntity">the type of the entity to get the datasource for</typeparam>
		''' <returns>the requested datasource</returns>
		public Function  GetQueryableForEntity(Of TEntity As class)() As DataSource2(Of TEntity)
			Return New DataSource2(Of TEntity)(Me.AdapterToUse, New ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse)
		End Function

		''' <summary>returns the datasource to use in a Linq query when targeting AttivitaEntity instances in the database.</summary>
		Public Readonly Property [Attivita] As DataSource2(Of AttivitaEntity)
			Get 
				Return New DataSource2(Of AttivitaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AttrezzaturaAttivitaEntity instances in the database.</summary>
		Public Readonly Property [AttrezzaturaAttivita] As DataSource2(Of AttrezzaturaAttivitaEntity)
			Get 
				Return New DataSource2(Of AttrezzaturaAttivitaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AuditEntity instances in the database.</summary>
		Public Readonly Property [Audit] As DataSource2(Of AuditEntity)
			Get 
				Return New DataSource2(Of AuditEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AziendaEntity instances in the database.</summary>
		Public Readonly Property [Azienda] As DataSource2(Of AziendaEntity)
			Get 
				Return New DataSource2(Of AziendaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AziendaProdottoEntity instances in the database.</summary>
		Public Readonly Property [AziendaProdotto] As DataSource2(Of AziendaProdottoEntity)
			Get 
				Return New DataSource2(Of AziendaProdottoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ComuneEntity instances in the database.</summary>
		Public Readonly Property [Comune] As DataSource2(Of ComuneEntity)
			Get 
				Return New DataSource2(Of ComuneEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ContattoEntity instances in the database.</summary>
		Public Readonly Property [Contatto] As DataSource2(Of ContattoEntity)
			Get 
				Return New DataSource2(Of ContattoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting DichiarazioneEntity instances in the database.</summary>
		Public Readonly Property [Dichiarazione] As DataSource2(Of DichiarazioneEntity)
			Get 
				Return New DataSource2(Of DichiarazioneEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting DichiarazioneOnLineEntity instances in the database.</summary>
		Public Readonly Property [DichiarazioneOnLine] As DataSource2(Of DichiarazioneOnLineEntity)
			Get 
				Return New DataSource2(Of DichiarazioneOnLineEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting EventoAziendaEntity instances in the database.</summary>
		Public Readonly Property [EventoAzienda] As DataSource2(Of EventoAziendaEntity)
			Get 
				Return New DataSource2(Of EventoAziendaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting IncassoEntity instances in the database.</summary>
		Public Readonly Property [Incasso] As DataSource2(Of IncassoEntity)
			Get 
				Return New DataSource2(Of IncassoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting LicenzaAziendaEntity instances in the database.</summary>
		Public Readonly Property [LicenzaAzienda] As DataSource2(Of LicenzaAziendaEntity)
			Get 
				Return New DataSource2(Of LicenzaAziendaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting MaterialeEntity instances in the database.</summary>
		Public Readonly Property [Materiale] As DataSource2(Of MaterialeEntity)
			Get 
				Return New DataSource2(Of MaterialeEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting MaterialeQuadroEntity instances in the database.</summary>
		Public Readonly Property [MaterialeQuadro] As DataSource2(Of MaterialeQuadroEntity)
			Get 
				Return New DataSource2(Of MaterialeQuadroEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ParametroEntity instances in the database.</summary>
		Public Readonly Property [Parametro] As DataSource2(Of ParametroEntity)
			Get 
				Return New DataSource2(Of ParametroEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ProdottoEntity instances in the database.</summary>
		Public Readonly Property [Prodotto] As DataSource2(Of ProdottoEntity)
			Get 
				Return New DataSource2(Of ProdottoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ProdottoDichiaratoEntity instances in the database.</summary>
		Public Readonly Property [ProdottoDichiarato] As DataSource2(Of ProdottoDichiaratoEntity)
			Get 
				Return New DataSource2(Of ProdottoDichiaratoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ProvinciaEntity instances in the database.</summary>
		Public Readonly Property [Provincia] As DataSource2(Of ProvinciaEntity)
			Get 
				Return New DataSource2(Of ProvinciaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting QuadroEntity instances in the database.</summary>
		Public Readonly Property [Quadro] As DataSource2(Of QuadroEntity)
			Get 
				Return New DataSource2(Of QuadroEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting RegioneEntity instances in the database.</summary>
		Public Readonly Property [Regione] As DataSource2(Of RegioneEntity)
			Get 
				Return New DataSource2(Of RegioneEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting RigaDichiarazioneEntity instances in the database.</summary>
		Public Readonly Property [RigaDichiarazione] As DataSource2(Of RigaDichiarazioneEntity)
			Get 
				Return New DataSource2(Of RigaDichiarazioneEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting RiunioneEntity instances in the database.</summary>
		Public Readonly Property [Riunione] As DataSource2(Of RiunioneEntity)
			Get 
				Return New DataSource2(Of RiunioneEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting RuoloUtenteEntity instances in the database.</summary>
		Public Readonly Property [RuoloUtente] As DataSource2(Of RuoloUtenteEntity)
			Get 
				Return New DataSource2(Of RuoloUtenteEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ScadenzaEntity instances in the database.</summary>
		Public Readonly Property [Scadenza] As DataSource2(Of ScadenzaEntity)
			Get 
				Return New DataSource2(Of ScadenzaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting SedeEntity instances in the database.</summary>
		Public Readonly Property [Sede] As DataSource2(Of SedeEntity)
			Get 
				Return New DataSource2(Of SedeEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting UtenteEntity instances in the database.</summary>
		Public Readonly Property [Utente] As DataSource2(Of UtenteEntity)
			Get 
				Return New DataSource2(Of UtenteEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AllegatoEntity instances in the database.</summary>
		Public Readonly Property [Allegato] As DataSource2(Of AllegatoEntity)
			Get 
				Return New DataSource2(Of AllegatoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AziendaAllegatoEntity instances in the database.</summary>
		Public Readonly Property [AziendaAllegato] As DataSource2(Of AziendaAllegatoEntity)
			Get 
				Return New DataSource2(Of AziendaAllegatoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting CodiciCerEntity instances in the database.</summary>
		Public Readonly Property [CodiciCer] As DataSource2(Of CodiciCerEntity)
			Get 
				Return New DataSource2(Of CodiciCerEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting DettaglioAllegatoEntity instances in the database.</summary>
		Public Readonly Property [DettaglioAllegato] As DataSource2(Of DettaglioAllegatoEntity)
			Get 
				Return New DataSource2(Of DettaglioAllegatoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting AliquotaIvaEntity instances in the database.</summary>
		Public Readonly Property [AliquotaIva] As DataSource2(Of AliquotaIvaEntity)
			Get 
				Return New DataSource2(Of AliquotaIvaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting CategoriaEntity instances in the database.</summary>
		Public Readonly Property [Categoria] As DataSource2(Of CategoriaEntity)
			Get 
				Return New DataSource2(Of CategoriaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting EventoEntity instances in the database.</summary>
		Public Readonly Property [Evento] As DataSource2(Of EventoEntity)
			Get 
				Return New DataSource2(Of EventoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting FormaGiuridicaEntity instances in the database.</summary>
		Public Readonly Property [FormaGiuridica] As DataSource2(Of FormaGiuridicaEntity)
			Get 
				Return New DataSource2(Of FormaGiuridicaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting InfoStatoEntity instances in the database.</summary>
		Public Readonly Property [InfoStato] As DataSource2(Of InfoStatoEntity)
			Get 
				Return New DataSource2(Of InfoStatoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting ModalitaPagamentoEntity instances in the database.</summary>
		Public Readonly Property [ModalitaPagamento] As DataSource2(Of ModalitaPagamentoEntity)
			Get 
				Return New DataSource2(Of ModalitaPagamentoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting QuotaAdesioneEntity instances in the database.</summary>
		Public Readonly Property [QuotaAdesione] As DataSource2(Of QuotaAdesioneEntity)
			Get 
				Return New DataSource2(Of QuotaAdesioneEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting RuoloContattoEntity instances in the database.</summary>
		Public Readonly Property [RuoloContatto] As DataSource2(Of RuoloContattoEntity)
			Get 
				Return New DataSource2(Of RuoloContattoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting StatoSocioEntity instances in the database.</summary>
		Public Readonly Property [StatoSocio] As DataSource2(Of StatoSocioEntity)
			Get 
				Return New DataSource2(Of StatoSocioEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoAttivitaEntity instances in the database.</summary>
		Public Readonly Property [TipoAttivita] As DataSource2(Of TipoAttivitaEntity)
			Get 
				Return New DataSource2(Of TipoAttivitaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoAttrezzaturaEntity instances in the database.</summary>
		Public Readonly Property [TipoAttrezzatura] As DataSource2(Of TipoAttrezzaturaEntity)
			Get 
				Return New DataSource2(Of TipoAttrezzaturaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoLicenzaEntity instances in the database.</summary>
		Public Readonly Property [TipoLicenza] As DataSource2(Of TipoLicenzaEntity)
			Get 
				Return New DataSource2(Of TipoLicenzaEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoMaterialeEntity instances in the database.</summary>
		Public Readonly Property [TipoMateriale] As DataSource2(Of TipoMaterialeEntity)
			Get 
				Return New DataSource2(Of TipoMaterialeEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoQuadroEntity instances in the database.</summary>
		Public Readonly Property [TipoQuadro] As DataSource2(Of TipoQuadroEntity)
			Get 
				Return New DataSource2(Of TipoQuadroEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoSedeEntity instances in the database.</summary>
		Public Readonly Property [TipoSede] As DataSource2(Of TipoSedeEntity)
			Get 
				Return New DataSource2(Of TipoSedeEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TipoSocioEntity instances in the database.</summary>
		Public Readonly Property [TipoSocio] As DataSource2(Of TipoSocioEntity)
			Get 
				Return New DataSource2(Of TipoSocioEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting TitoloContattoEntity instances in the database.</summary>
		Public Readonly Property [TitoloContatto] As DataSource2(Of TitoloContattoEntity)
			Get 
				Return New DataSource2(Of TitoloContattoEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		
		''' <summary>returns the datasource to use in a Linq query when targeting UnitaMisuraEntity instances in the database.</summary>
		Public Readonly Property [UnitaMisura] As DataSource2(Of UnitaMisuraEntity)
			Get 
				Return New DataSource2(Of UnitaMisuraEntity)(Me.AdapterToUse, new ElementCreator(), Me.CustomFunctionMappings, Me.ContextToUse) 
			End Get
		End Property
		

		''' <summary> Gets / sets the IDataAccessAdapter To use For the queries created With this meta data Object.</summary>
		''' <remarks> Be aware that the IDataAccessAdapter Object Set via this Property Is kept alive by the LLBLGenProQuery objects created With this meta data till they go out of scope.</remarks>
		Public Property AdapterToUse As IDataAccessAdapter
		
		''' <summary>Gets Or sets the custom Function mappings To use. These take higher precedence than the ones In the DQE To use</summary>
		Public Property CustomFunctionMappings As FunctionMappingStore 
						
		''' <summary>Gets Or sets the Context instance To use For entity fetches.</summary>
		Public Property ContextToUse As Context
	End Class
End Namespace