' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' // Templates version: 
' //////////////////////////////////////////////////////////////
Imports System
Imports System.Runtime.Serialization
Imports System.Collections.Generic
Imports SD.LLBLGen.Pro.ORMSupportClasses

Namespace DAL.HelperClasses
	''' <summary>Helper class which will eases the creation of custom made resultsets. Usable in typed lists and dynamic lists created Imports the dynamic query engine.</summary>
	<Serializable()> _
	Public Class ResultsetFields 
		Inherits EntityFields2
	
		''' <summary>CTor</summary>
		Public Sub New(amountFields As Integer)
			MyBase.New(amountFields, ModelInfoProviderSingleton.GetInstance(), Nothing)
		End Sub
				
		''' <summary>Deserialization constructor</summary>
		''' <param name="info">Info.</param>
		''' <param name="context">Context.</param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext )
			MyBase.New(info.GetInt32("_amountFields"), ModelInfoProviderSingleton.GetInstance(), Nothing)
			PerformDeserializationInitialization(info)
		End Sub

	End Class
End Namespace
