' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' ////////////////////////////////////////////////////////////////////////////////////////////////////////
Imports System
Imports SD.LLBLGen.Pro.ORMSupportClasses

Namespace DAL.HelperClasses
	''' <summary>Class for the returning of a default value when a type is given. These Default values are used for EntityFields which have a NULL value in the database.
	''' To customize the values returned by this class, please implement the partial method <see cref="PostProcessValueToReturn"/> in a partial class of this class.</summary>
	<Serializable> _
	Public Class TypeDefaultValue 
		Implements ITypeDefaultValue
	
		''' <summary>Partial method which allows the default value currently chosen to be changed based on custom code</summary>
		''' <param name="defaultValueType">The type which default value should be returned.</param>
		''' <param name="currentValue">The currently chosen value for the type specified.</param>
		Partial Private Sub PostProcessValueToReturn(defaultValueType as System.Type, ByRef currentValue as Object)
		End Sub
	
		''' <summary>Ctor</summary>
		Public Sub New()
		End Sub

		''' <summary>
		''' Returns a default value for the type specified
		''' </summary>
		''' <param name="defaultValueType">The type which default value should be returned.</param>
		''' <returns>The default value for the type specified.</returns>
		Public Function DefaultValue(defaultValueType As System.Type) As Object Implements ITypeDefaultValue.DefaultValue
			Dim toReturn = TypeDefaultValue.GetDefaultValue(defaultValueType)
			PostProcessValueToReturn(defaultValueType, toReturn)
			Return toReturn
		End Function

		''' <summary>
		''' Returns a default value for the type specified
		''' </summary>
		''' <param name="defaultValueType">The type which default value should be returned.</param>
		''' <returns>The default value for the type specified.</returns>
		Public Shared Function GetDefaultValue(defaultValueType As System.Type) As Object
			Dim valueToReturn As Object = Nothing

			Select Case Type.GetTypeCode(defaultValueType)
				Case TypeCode.Boolean
					valueToReturn = False
				Case TypeCode.Byte
					valueToReturn = CByte(0)
				Case TypeCode.DateTime
					valueToReturn = DateTime.MinValue
				Case TypeCode.Decimal
					valueToReturn = 0.0D
				Case TypeCode.Double
					valueToReturn = 0.0R
				Case TypeCode.Int16
					valueToReturn = CShort(0)
				Case TypeCode.Int32
					valueToReturn = CInt(0)
				Case TypeCode.Int64
					valueToReturn = CLng(0)
				Case TypeCode.Object
					Select Case defaultValueType.UnderlyingSystemType.FullName
						Case "System.Byte[]"
							valueToReturn = New Byte(-1) {}
						Case "System.Guid"
							valueToReturn = Guid.Empty
						case "System.DateTimeOffset"
							valueToReturn = DateTimeOffset.MinValue
						case "System.TimeSpan"
							valueToReturn = TimeSpan.MinValue
					End Select
				Case TypeCode.String
					valueToReturn=String.Empty
				Case TypeCode.Single
					valueToReturn = 0.0F
				case TypeCode.UInt16
					valueToReturn = 0US
				case TypeCode.UInt32
					valueToReturn = 0UI
				case TypeCode.UInt64
					valueToReturn = 0US
				Case Else
					' do nothing, return Nothing.
			End Select
			Return valueToReturn

		End Function

	End Class
End Namespace

