'//////////////////////////////////////////////////////////////
'// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
'//////////////////////////////////////////////////////////////
'// Code Is generated On: 
'// Code Is generated Using templates: SD.TemplateBindings.SharedTemplates
'// Templates vendor: Solutions Design.
'///////////////////////////////////////////////////////////''' 
Imports System
Imports System.Linq
Imports DAL.EntityClasses
Imports DAL.HelperClasses
Imports SD.LLBLGen.Pro.ORMSupportClasses
Imports SD.LLBLGen.Pro.QuerySpec.AdapterSpecific
Imports SD.LLBLGen.Pro.QuerySpec

Namespace DAL.FactoryClasses
	''' <summary>Factory Class To produce DynamicQuery instances And EntityQuery instances</summary>
	Public Class QueryFactory
		Inherits QueryFactoryBase2
		''' <summary>Creates And returns a New EntityQuery For the Attivita entity</summary>
		Public ReadOnly Property [Attivita] As EntityQuery(Of AttivitaEntity)
			Get
				Return Create(Of AttivitaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the AttrezzaturaAttivita entity</summary>
		Public ReadOnly Property [AttrezzaturaAttivita] As EntityQuery(Of AttrezzaturaAttivitaEntity)
			Get
				Return Create(Of AttrezzaturaAttivitaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Audit entity</summary>
		Public ReadOnly Property [Audit] As EntityQuery(Of AuditEntity)
			Get
				Return Create(Of AuditEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Azienda entity</summary>
		Public ReadOnly Property [Azienda] As EntityQuery(Of AziendaEntity)
			Get
				Return Create(Of AziendaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the AziendaProdotto entity</summary>
		Public ReadOnly Property [AziendaProdotto] As EntityQuery(Of AziendaProdottoEntity)
			Get
				Return Create(Of AziendaProdottoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Comune entity</summary>
		Public ReadOnly Property [Comune] As EntityQuery(Of ComuneEntity)
			Get
				Return Create(Of ComuneEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Contatto entity</summary>
		Public ReadOnly Property [Contatto] As EntityQuery(Of ContattoEntity)
			Get
				Return Create(Of ContattoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Dichiarazione entity</summary>
		Public ReadOnly Property [Dichiarazione] As EntityQuery(Of DichiarazioneEntity)
			Get
				Return Create(Of DichiarazioneEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the DichiarazioneOnLine entity</summary>
		Public ReadOnly Property [DichiarazioneOnLine] As EntityQuery(Of DichiarazioneOnLineEntity)
			Get
				Return Create(Of DichiarazioneOnLineEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the EventoAzienda entity</summary>
		Public ReadOnly Property [EventoAzienda] As EntityQuery(Of EventoAziendaEntity)
			Get
				Return Create(Of EventoAziendaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Incasso entity</summary>
		Public ReadOnly Property [Incasso] As EntityQuery(Of IncassoEntity)
			Get
				Return Create(Of IncassoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the LicenzaAzienda entity</summary>
		Public ReadOnly Property [LicenzaAzienda] As EntityQuery(Of LicenzaAziendaEntity)
			Get
				Return Create(Of LicenzaAziendaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Materiale entity</summary>
		Public ReadOnly Property [Materiale] As EntityQuery(Of MaterialeEntity)
			Get
				Return Create(Of MaterialeEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the MaterialeQuadro entity</summary>
		Public ReadOnly Property [MaterialeQuadro] As EntityQuery(Of MaterialeQuadroEntity)
			Get
				Return Create(Of MaterialeQuadroEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Parametro entity</summary>
		Public ReadOnly Property [Parametro] As EntityQuery(Of ParametroEntity)
			Get
				Return Create(Of ParametroEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Prodotto entity</summary>
		Public ReadOnly Property [Prodotto] As EntityQuery(Of ProdottoEntity)
			Get
				Return Create(Of ProdottoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the ProdottoDichiarato entity</summary>
		Public ReadOnly Property [ProdottoDichiarato] As EntityQuery(Of ProdottoDichiaratoEntity)
			Get
				Return Create(Of ProdottoDichiaratoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Provincia entity</summary>
		Public ReadOnly Property [Provincia] As EntityQuery(Of ProvinciaEntity)
			Get
				Return Create(Of ProvinciaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Quadro entity</summary>
		Public ReadOnly Property [Quadro] As EntityQuery(Of QuadroEntity)
			Get
				Return Create(Of QuadroEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Regione entity</summary>
		Public ReadOnly Property [Regione] As EntityQuery(Of RegioneEntity)
			Get
				Return Create(Of RegioneEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the RigaDichiarazione entity</summary>
		Public ReadOnly Property [RigaDichiarazione] As EntityQuery(Of RigaDichiarazioneEntity)
			Get
				Return Create(Of RigaDichiarazioneEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Riunione entity</summary>
		Public ReadOnly Property [Riunione] As EntityQuery(Of RiunioneEntity)
			Get
				Return Create(Of RiunioneEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the RuoloUtente entity</summary>
		Public ReadOnly Property [RuoloUtente] As EntityQuery(Of RuoloUtenteEntity)
			Get
				Return Create(Of RuoloUtenteEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Scadenza entity</summary>
		Public ReadOnly Property [Scadenza] As EntityQuery(Of ScadenzaEntity)
			Get
				Return Create(Of ScadenzaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Sede entity</summary>
		Public ReadOnly Property [Sede] As EntityQuery(Of SedeEntity)
			Get
				Return Create(Of SedeEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Utente entity</summary>
		Public ReadOnly Property [Utente] As EntityQuery(Of UtenteEntity)
			Get
				Return Create(Of UtenteEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Allegato entity</summary>
		Public ReadOnly Property [Allegato] As EntityQuery(Of AllegatoEntity)
			Get
				Return Create(Of AllegatoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the AziendaAllegato entity</summary>
		Public ReadOnly Property [AziendaAllegato] As EntityQuery(Of AziendaAllegatoEntity)
			Get
				Return Create(Of AziendaAllegatoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the CodiciCer entity</summary>
		Public ReadOnly Property [CodiciCer] As EntityQuery(Of CodiciCerEntity)
			Get
				Return Create(Of CodiciCerEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the DettaglioAllegato entity</summary>
		Public ReadOnly Property [DettaglioAllegato] As EntityQuery(Of DettaglioAllegatoEntity)
			Get
				Return Create(Of DettaglioAllegatoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the AliquotaIva entity</summary>
		Public ReadOnly Property [AliquotaIva] As EntityQuery(Of AliquotaIvaEntity)
			Get
				Return Create(Of AliquotaIvaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Categoria entity</summary>
		Public ReadOnly Property [Categoria] As EntityQuery(Of CategoriaEntity)
			Get
				Return Create(Of CategoriaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the Evento entity</summary>
		Public ReadOnly Property [Evento] As EntityQuery(Of EventoEntity)
			Get
				Return Create(Of EventoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the FormaGiuridica entity</summary>
		Public ReadOnly Property [FormaGiuridica] As EntityQuery(Of FormaGiuridicaEntity)
			Get
				Return Create(Of FormaGiuridicaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the InfoStato entity</summary>
		Public ReadOnly Property [InfoStato] As EntityQuery(Of InfoStatoEntity)
			Get
				Return Create(Of InfoStatoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the ModalitaPagamento entity</summary>
		Public ReadOnly Property [ModalitaPagamento] As EntityQuery(Of ModalitaPagamentoEntity)
			Get
				Return Create(Of ModalitaPagamentoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the QuotaAdesione entity</summary>
		Public ReadOnly Property [QuotaAdesione] As EntityQuery(Of QuotaAdesioneEntity)
			Get
				Return Create(Of QuotaAdesioneEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the RuoloContatto entity</summary>
		Public ReadOnly Property [RuoloContatto] As EntityQuery(Of RuoloContattoEntity)
			Get
				Return Create(Of RuoloContattoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the StatoSocio entity</summary>
		Public ReadOnly Property [StatoSocio] As EntityQuery(Of StatoSocioEntity)
			Get
				Return Create(Of StatoSocioEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoAttivita entity</summary>
		Public ReadOnly Property [TipoAttivita] As EntityQuery(Of TipoAttivitaEntity)
			Get
				Return Create(Of TipoAttivitaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoAttrezzatura entity</summary>
		Public ReadOnly Property [TipoAttrezzatura] As EntityQuery(Of TipoAttrezzaturaEntity)
			Get
				Return Create(Of TipoAttrezzaturaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoLicenza entity</summary>
		Public ReadOnly Property [TipoLicenza] As EntityQuery(Of TipoLicenzaEntity)
			Get
				Return Create(Of TipoLicenzaEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoMateriale entity</summary>
		Public ReadOnly Property [TipoMateriale] As EntityQuery(Of TipoMaterialeEntity)
			Get
				Return Create(Of TipoMaterialeEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoQuadro entity</summary>
		Public ReadOnly Property [TipoQuadro] As EntityQuery(Of TipoQuadroEntity)
			Get
				Return Create(Of TipoQuadroEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoSede entity</summary>
		Public ReadOnly Property [TipoSede] As EntityQuery(Of TipoSedeEntity)
			Get
				Return Create(Of TipoSedeEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TipoSocio entity</summary>
		Public ReadOnly Property [TipoSocio] As EntityQuery(Of TipoSocioEntity)
			Get
				Return Create(Of TipoSocioEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the TitoloContatto entity</summary>
		Public ReadOnly Property [TitoloContatto] As EntityQuery(Of TitoloContattoEntity)
			Get
				Return Create(Of TitoloContattoEntity)()
			End Get
		End Property

		''' <summary>Creates And returns a New EntityQuery For the UnitaMisura entity</summary>
		Public ReadOnly Property [UnitaMisura] As EntityQuery(Of UnitaMisuraEntity)
			Get
				Return Create(Of UnitaMisuraEntity)()
			End Get
		End Property

		''' <inheritdoc/>
		Protected Overrides Function CreateElementCreator() As IElementCreatorCore 
			Return New ElementCreator()
		End Function
 
	End Class
End Namespace