' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Collections
Imports System.Runtime.Serialization
Imports DAL.EntityClasses
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports SD.LLBLGen.Pro.ORMSupportClasses
Imports SD.LLBLGen.Pro.QuerySpec


' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.TypedListClasses

	''' <summary>Typed datatable for the list 'LstSoci'.<br/><br/></summary>
	<Serializable(), System.ComponentModel.DesignerCategory("Code"), ToolboxItem(True), DesignTimeVisible(True)> _
	Public Class LstSociTypedList 
		Inherits TypedListBase2(Of LstSociRow)
		Implements ITypedListLgp2

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfacesList
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _columnAllegaBilancio As DataColumn
		Private _columnAssociazione As DataColumn
		Private _columnCap As DataColumn
		Private _columnCodCategoria As DataColumn
		Private _columnCodiceFiscale As DataColumn
		Private _columnDataAdesione As DataColumn
		Private _columnDataAssemblea As DataColumn
		Private _columnDataInizioAttivita As DataColumn
		Private _columnDataPassaggioCda As DataColumn
		Private _columnDataVersamentoUnaTantum As DataColumn
		Private _columnDocumentazioneCciaa As DataColumn
		Private _columnEmail As DataColumn
		Private _columnFax As DataColumn
		Private _columnId As DataColumn
		Private _columnIndirizzo As DataColumn
		Private _columnCodInfoStato As DataColumn
		Private _columnLegaleRappresentante As DataColumn
		Private _columnLocalita As DataColumn
		Private _columnPartitaIva As DataColumn
		Private _columnProvincia As DataColumn
		Private _columnQuotaAdesione As DataColumn
		Private _columnRagioneSociale As DataColumn
		Private _columnRegione As DataColumn
		Private _columnCodStato As DataColumn
		Private _columnStatoDichiarazione As DataColumn
		Private _columnStatoPagamenti As DataColumn
		Private _columnTelefono1 As DataColumn
		Private _columnTelefono2 As DataColumn
		Private _columnCodTipoIscrizione As DataColumn
		Private _columnCodFormaGiuridica As DataColumn
		Private _columnUsatoPerSpedizione As DataColumn
		Private _fields As ResultsetFields
		Private _filterBucket As IRelationPredicateBucket 
		
		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _customProperties As Hashtable
		Private Shared _fieldsCustomProperties As Hashtable
		Private Const AmountOfFields As Integer = 31
		
		''' <summary>Static CTor for setting up custom property hashtables.</summary>
		Shared Sub New()
			SetupCustomPropertyHashtables()
		End Sub

		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New("LstSoci")
			InitClass(False)
		End Sub	
		
		''' <summary>CTor</summary>
		''' <param name="obeyWeakRelations">The flag to signal the collection what kind of join statements to generate in the query statement.</param>
		Public Sub New(obeyWeakRelations As Boolean)
			MyBase.New("LstSoci")
			InitClass(obeyWeakRelations)
		End Sub

		''' <summary>Protected constructor for deserialization.</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			If SerializationHelper.Optimization = SerializationOptimization.None Then
				InitMembers()
				BuildResultset()
			End If
		End Sub

		''' <summary>Gets the IEntityFields2 collection of fields of this typed list.</summary>
		''' <returns>Ready to use IEntityFields2 collection object.</returns>
		Public Function GetFieldsInfo() As IEntityFields2 Implements ITypedListLgp2.GetFieldsInfo
			Return _fields
		End Function

		''' <summary>Gets the IRelationPredicateBucket object which contains the relation information for this Typed List.</summary>
		''' <returns>Ready to use IRelationPredicateBucket object.</returns>
		Public Function GetRelationInfo() As IRelationPredicateBucket Implements ITypedListLgp2.GetRelationInfo
			_filterBucket = New RelationPredicateBucket()
			BuildRelationSet()
			Return _filterBucket
		End Function
				
		''' <summary>Gets the QuerySpec query which fetches this typed list.</summary>
		''' <param name="qf">The queryfactory.</param>
		''' <returns>ready to use DynamicQuery instance to be used with FetchAsDataTable in the QuerySpec API</returns>
		Public Function GetQuerySpecQuery(qf As QueryFactory) As DynamicQuery 
			Return qf.Create().Select(Me.GetFieldsInfo().GetAsEntityFieldCoreArray()).From(Me.GetRelationInfo().Relations)
		End Function

		''' <summary>Creates a New typed row during the build of the datatable during a Fill session by a dataadapter.</summary>
		''' <param name="rowBuilder">supplied row builder to pass to the typed row</param>
		''' <returns>the New typed datarow</returns>
		Protected Overrides Function NewRowFromBuilder(rowBuilder As DataRowBuilder) As DataRow
			Return New LstSociRow(rowBuilder)
		End Function

		''' <summary>
		''' Builds the relation set for this typed list, inside the filterBucket object.
		''' </summary>
		Private Sub BuildRelationSet()
			_filterBucket.Relations.ObeyWeakRelations = MyBase.ObeyWeakRelations

			
			' __LLBLGENPRO_USER_CODE_REGION_START AdditionalRelations
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnRelationSetBuilt(_filterBucket.Relations)
		End Sub

		''' <summary>
		''' Builds the resultset fields, stored in the Private _fields object
		''' </summary>
		Private Sub BuildResultset()
			_fields = New ResultsetFields(AmountOfFields)
			_fields.DefineField(AziendaFields.AllegaBilancio, 0, "AllegaBilancio", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Associazione, 1, "Associazione", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Cap, 2, "Cap", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.CodCategoria, 3, "CodCategoria", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.CodiceFiscale, 4, "CodiceFiscale", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.DataAdesione, 5, "DataAdesione", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.DataAssemblea, 6, "DataAssemblea", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.DataInizioAttivita, 7, "DataInizioAttivita", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.DataPassaggioCda, 8, "DataPassaggioCda", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.DataVersamentoUnaTantum, 9, "DataVersamentoUnaTantum", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.DocumentazioneCciaa, 10, "DocumentazioneCciaa", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Email, 11, "Email", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Fax, 12, "Fax", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Id, 13, "Id", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Indirizzo, 14, "Indirizzo", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.CodInfoStato, 15, "CodInfoStato", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.LegaleRappresentante, 16, "LegaleRappresentante", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Localita, 17, "Localita", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.PartitaIva, 18, "PartitaIva", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Provincia, 19, "Provincia", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.QuotaAdesione, 20, "QuotaAdesione", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.RagioneSociale, 21, "RagioneSociale", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Regione, 22, "Regione", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.CodStato, 23, "CodStato", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.StatoDichiarazione, 24, "StatoDichiarazione", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.StatoPagamenti, 25, "StatoPagamenti", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Telefono1, 26, "Telefono1", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.Telefono2, 27, "Telefono2", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.CodTipoIscrizione, 28, "CodTipoIscrizione", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.CodFormaGiuridica, 29, "CodFormaGiuridica", "", AggregateFunction.None)
			_fields.DefineField(AziendaFields.UsatoPerSpedizione, 30, "UsatoPerSpedizione", "", AggregateFunction.None)
			
			' __LLBLGENPRO_USER_CODE_REGION_START AdditionalFields
			' be sure To call _fields.Expand(number of New fields) first. 
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnResultsetBuilt(_fields)
		End Sub

		''' <summary>
		''' Initialize the datastructures.
		''' </summary>
		''' <param name="obeyWeakRelations">flag for the internal used relations object</param>
		Protected Overrides Sub InitClass(obeyWeakRelations As Boolean)
			TableName = "LstSoci"
			Me.ObeyWeakRelations = obeyWeakRelations
			_columnAllegaBilancio = GeneralUtils.CreateTypedDataTableColumn("AllegaBilancio", "AllegaBilancio", GetType(System.Boolean), Me.Columns)
			_columnAssociazione = GeneralUtils.CreateTypedDataTableColumn("Associazione", "Associazione", GetType(System.String), Me.Columns)
			_columnCap = GeneralUtils.CreateTypedDataTableColumn("Cap", "Cap", GetType(System.String), Me.Columns)
			_columnCodCategoria = GeneralUtils.CreateTypedDataTableColumn("CodCategoria", "Categoria", GetType(System.String), Me.Columns)
			_columnCodiceFiscale = GeneralUtils.CreateTypedDataTableColumn("CodiceFiscale", "CodiceFiscale", GetType(System.String), Me.Columns)
			_columnDataAdesione = GeneralUtils.CreateTypedDataTableColumn("DataAdesione", "DataAdesione", GetType(System.DateTime), Me.Columns)
			_columnDataAssemblea = GeneralUtils.CreateTypedDataTableColumn("DataAssemblea", "DataAssemblea", GetType(System.DateTime), Me.Columns)
			_columnDataInizioAttivita = GeneralUtils.CreateTypedDataTableColumn("DataInizioAttivita", "DataInizioAttivita", GetType(System.DateTime), Me.Columns)
			_columnDataPassaggioCda = GeneralUtils.CreateTypedDataTableColumn("DataPassaggioCda", "DataPassaggioCda", GetType(System.DateTime), Me.Columns)
			_columnDataVersamentoUnaTantum = GeneralUtils.CreateTypedDataTableColumn("DataVersamentoUnaTantum", "DataVersamentoUnaTantum", GetType(System.DateTime), Me.Columns)
			_columnDocumentazioneCciaa = GeneralUtils.CreateTypedDataTableColumn("DocumentazioneCciaa", "DocumentazioneCciaa", GetType(System.Boolean), Me.Columns)
			_columnEmail = GeneralUtils.CreateTypedDataTableColumn("Email", "Email", GetType(System.String), Me.Columns)
			_columnFax = GeneralUtils.CreateTypedDataTableColumn("Fax", "Fax", GetType(System.String), Me.Columns)
			_columnId = GeneralUtils.CreateTypedDataTableColumn("Id", "Id", GetType(System.Int32), Me.Columns)
			_columnIndirizzo = GeneralUtils.CreateTypedDataTableColumn("Indirizzo", "Indirizzo", GetType(System.String), Me.Columns)
			_columnCodInfoStato = GeneralUtils.CreateTypedDataTableColumn("CodInfoStato", "InfoStato", GetType(System.String), Me.Columns)
			_columnLegaleRappresentante = GeneralUtils.CreateTypedDataTableColumn("LegaleRappresentante", "LegaleRappresentante", GetType(System.String), Me.Columns)
			_columnLocalita = GeneralUtils.CreateTypedDataTableColumn("Localita", "Localita", GetType(System.String), Me.Columns)
			_columnPartitaIva = GeneralUtils.CreateTypedDataTableColumn("PartitaIva", "PartitaIva", GetType(System.String), Me.Columns)
			_columnProvincia = GeneralUtils.CreateTypedDataTableColumn("Provincia", "Provincia", GetType(System.String), Me.Columns)
			_columnQuotaAdesione = GeneralUtils.CreateTypedDataTableColumn("QuotaAdesione", "QuotaAdesione", GetType(System.Decimal), Me.Columns)
			_columnRagioneSociale = GeneralUtils.CreateTypedDataTableColumn("RagioneSociale", "RagioneSociale", GetType(System.String), Me.Columns)
			_columnRegione = GeneralUtils.CreateTypedDataTableColumn("Regione", "Regione", GetType(System.String), Me.Columns)
			_columnCodStato = GeneralUtils.CreateTypedDataTableColumn("CodStato", "Stato", GetType(System.String), Me.Columns)
			_columnStatoDichiarazione = GeneralUtils.CreateTypedDataTableColumn("StatoDichiarazione", "StatoDichiarazione", GetType(System.String), Me.Columns)
			_columnStatoPagamenti = GeneralUtils.CreateTypedDataTableColumn("StatoPagamenti", "StatoPagamenti", GetType(System.String), Me.Columns)
			_columnTelefono1 = GeneralUtils.CreateTypedDataTableColumn("Telefono1", "Telefono1", GetType(System.String), Me.Columns)
			_columnTelefono2 = GeneralUtils.CreateTypedDataTableColumn("Telefono2", "Telefono2", GetType(System.String), Me.Columns)
			_columnCodTipoIscrizione = GeneralUtils.CreateTypedDataTableColumn("CodTipoIscrizione", "TipoIscrizione", GetType(System.String), Me.Columns)
			_columnCodFormaGiuridica = GeneralUtils.CreateTypedDataTableColumn("CodFormaGiuridica", "TipoSocieta", GetType(System.String), Me.Columns)
			_columnUsatoPerSpedizione = GeneralUtils.CreateTypedDataTableColumn("UsatoPerSpedizione", "UsatoPerSpedizione", GetType(System.Boolean), Me.Columns)

			' __LLBLGENPRO_USER_CODE_REGION_START InitClass
			' __LLBLGENPRO_USER_CODE_REGION_END
			BuildResultset()
			_filterBucket = New RelationPredicateBucket()
			BuildRelationSet()
			OnInitialized()
		End Sub

		''' <summary>
		''' Initializes the members, after a clone action.
		''' </summary>
		Private Sub InitMembers()
			_columnAllegaBilancio = Me.Columns("AllegaBilancio")
			_columnAssociazione = Me.Columns("Associazione")
			_columnCap = Me.Columns("Cap")
			_columnCodCategoria = Me.Columns("CodCategoria")
			_columnCodiceFiscale = Me.Columns("CodiceFiscale")
			_columnDataAdesione = Me.Columns("DataAdesione")
			_columnDataAssemblea = Me.Columns("DataAssemblea")
			_columnDataInizioAttivita = Me.Columns("DataInizioAttivita")
			_columnDataPassaggioCda = Me.Columns("DataPassaggioCda")
			_columnDataVersamentoUnaTantum = Me.Columns("DataVersamentoUnaTantum")
			_columnDocumentazioneCciaa = Me.Columns("DocumentazioneCciaa")
			_columnEmail = Me.Columns("Email")
			_columnFax = Me.Columns("Fax")
			_columnId = Me.Columns("Id")
			_columnIndirizzo = Me.Columns("Indirizzo")
			_columnCodInfoStato = Me.Columns("CodInfoStato")
			_columnLegaleRappresentante = Me.Columns("LegaleRappresentante")
			_columnLocalita = Me.Columns("Localita")
			_columnPartitaIva = Me.Columns("PartitaIva")
			_columnProvincia = Me.Columns("Provincia")
			_columnQuotaAdesione = Me.Columns("QuotaAdesione")
			_columnRagioneSociale = Me.Columns("RagioneSociale")
			_columnRegione = Me.Columns("Regione")
			_columnCodStato = Me.Columns("CodStato")
			_columnStatoDichiarazione = Me.Columns("StatoDichiarazione")
			_columnStatoPagamenti = Me.Columns("StatoPagamenti")
			_columnTelefono1 = Me.Columns("Telefono1")
			_columnTelefono2 = Me.Columns("Telefono2")
			_columnCodTipoIscrizione = Me.Columns("CodTipoIscrizione")
			_columnCodFormaGiuridica = Me.Columns("CodFormaGiuridica")
			_columnUsatoPerSpedizione = Me.Columns("UsatoPerSpedizione")
			
			' __LLBLGENPRO_USER_CODE_REGION_START InitMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitialized()
		End Sub

		''' <summary>
		''' Initializes the hashtables for the TypedList type and TypedList field custom properties. 
		''' </summary>
		Private Shared Sub SetupCustomPropertyHashtables()
			_customProperties = New Hashtable()
			_fieldsCustomProperties = New Hashtable()
			Dim fieldHashtable As Hashtable = Nothing
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("AllegaBilancio", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Associazione", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Cap", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("CodCategoria", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("CodiceFiscale", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("DataAdesione", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("DataAssemblea", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("DataInizioAttivita", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("DataPassaggioCda", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("DataVersamentoUnaTantum", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("DocumentazioneCciaa", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Email", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Fax", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Id", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Indirizzo", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("CodInfoStato", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("LegaleRappresentante", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Localita", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("PartitaIva", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Provincia", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("QuotaAdesione", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("RagioneSociale", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Regione", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("CodStato", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("StatoDichiarazione", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("StatoPagamenti", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Telefono1", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("Telefono2", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("CodTipoIscrizione", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("CodFormaGiuridica", fieldHashtable)
			fieldHashtable = New Hashtable()
			_fieldsCustomProperties.Add("UsatoPerSpedizione", fieldHashtable)
		End Sub

		''' <summary>
		''' Clones this instance.
		''' </summary>
		''' <returns>A clone of this instance</returns>
		Public Overrides Function Clone() As DataTable
			Dim cloneToReturn As LstSociTypedList = CType(MyBase.Clone(), LstSociTypedList)
			cloneToReturn.InitMembers()
			Return cloneToReturn
		End Function

		''' <summary>
		''' Creates a New instance of the DataTable class.
		''' </summary>
		''' <returns>a New instance of a datatable with this schema.</returns>
		Protected Overrides Function CreateInstance() As DataTable
			Return New LstSociTypedList()
		End Function

		''' <summary>
		''' The custom properties for this TypedList type.
		''' </summary>
		''' <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		Public Shared ReadOnly Property CustomProperties() As Hashtable
			Get
				Return _customProperties
			End Get
		End Property

		''' <summary>
		''' The custom properties for the type of this TypedList instance.
		''' </summary>
		''' <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		<System.ComponentModel.Browsable(False)> _
		Public Overridable ReadOnly Property CustomPropertiesOfType() As Hashtable
			Get
				Return LstSociTypedList.CustomProperties
			End Get
		End Property

		''' <summary>
		''' The custom properties for the fields of this TypedList type. The returned Hashtable contains per fieldname a hashtable of name-value pairs. 
		''' </summary>
		''' <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		Public Shared ReadOnly Property FieldsCustomProperties() As Hashtable
			Get
				Return _fieldsCustomProperties
			End Get
		End Property

		''' <summary>
		''' The custom properties for the fields of the type of this TypedList instance. The returned Hashtable contains per fieldname a hashtable of name-value
		''' pairs. 
		''' </summary>
		''' <remarks>The data returned from this property should be considered read-only: it is not thread safe to alter this data at runtime.</remarks>
		<System.ComponentModel.Browsable(False)> _
		Public Overridable ReadOnly Property FieldsCustomPropertiesOfType() As Hashtable
			Get
				Return LstSociTypedList.FieldsCustomProperties
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field AllegaBilancio</summary>
		ReadOnly Friend Property AllegaBilancioColumn As DataColumn
			Get 
				Return _columnAllegaBilancio 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Associazione</summary>
		ReadOnly Friend Property AssociazioneColumn As DataColumn
			Get 
				Return _columnAssociazione 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Cap</summary>
		ReadOnly Friend Property CapColumn As DataColumn
			Get 
				Return _columnCap 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field CodCategoria</summary>
		ReadOnly Friend Property CodCategoriaColumn As DataColumn
			Get 
				Return _columnCodCategoria 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field CodiceFiscale</summary>
		ReadOnly Friend Property CodiceFiscaleColumn As DataColumn
			Get 
				Return _columnCodiceFiscale 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field DataAdesione</summary>
		ReadOnly Friend Property DataAdesioneColumn As DataColumn
			Get 
				Return _columnDataAdesione 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field DataAssemblea</summary>
		ReadOnly Friend Property DataAssembleaColumn As DataColumn
			Get 
				Return _columnDataAssemblea 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field DataInizioAttivita</summary>
		ReadOnly Friend Property DataInizioAttivitaColumn As DataColumn
			Get 
				Return _columnDataInizioAttivita 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field DataPassaggioCda</summary>
		ReadOnly Friend Property DataPassaggioCdaColumn As DataColumn
			Get 
				Return _columnDataPassaggioCda 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field DataVersamentoUnaTantum</summary>
		ReadOnly Friend Property DataVersamentoUnaTantumColumn As DataColumn
			Get 
				Return _columnDataVersamentoUnaTantum 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field DocumentazioneCciaa</summary>
		ReadOnly Friend Property DocumentazioneCciaaColumn As DataColumn
			Get 
				Return _columnDocumentazioneCciaa 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Email</summary>
		ReadOnly Friend Property EmailColumn As DataColumn
			Get 
				Return _columnEmail 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Fax</summary>
		ReadOnly Friend Property FaxColumn As DataColumn
			Get 
				Return _columnFax 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Id</summary>
		ReadOnly Friend Property IdColumn As DataColumn
			Get 
				Return _columnId 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Indirizzo</summary>
		ReadOnly Friend Property IndirizzoColumn As DataColumn
			Get 
				Return _columnIndirizzo 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field CodInfoStato</summary>
		ReadOnly Friend Property CodInfoStatoColumn As DataColumn
			Get 
				Return _columnCodInfoStato 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field LegaleRappresentante</summary>
		ReadOnly Friend Property LegaleRappresentanteColumn As DataColumn
			Get 
				Return _columnLegaleRappresentante 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Localita</summary>
		ReadOnly Friend Property LocalitaColumn As DataColumn
			Get 
				Return _columnLocalita 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field PartitaIva</summary>
		ReadOnly Friend Property PartitaIvaColumn As DataColumn
			Get 
				Return _columnPartitaIva 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Provincia</summary>
		ReadOnly Friend Property ProvinciaColumn As DataColumn
			Get 
				Return _columnProvincia 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field QuotaAdesione</summary>
		ReadOnly Friend Property QuotaAdesioneColumn As DataColumn
			Get 
				Return _columnQuotaAdesione 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field RagioneSociale</summary>
		ReadOnly Friend Property RagioneSocialeColumn As DataColumn
			Get 
				Return _columnRagioneSociale 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Regione</summary>
		ReadOnly Friend Property RegioneColumn As DataColumn
			Get 
				Return _columnRegione 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field CodStato</summary>
		ReadOnly Friend Property CodStatoColumn As DataColumn
			Get 
				Return _columnCodStato 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field StatoDichiarazione</summary>
		ReadOnly Friend Property StatoDichiarazioneColumn As DataColumn
			Get 
				Return _columnStatoDichiarazione 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field StatoPagamenti</summary>
		ReadOnly Friend Property StatoPagamentiColumn As DataColumn
			Get 
				Return _columnStatoPagamenti 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Telefono1</summary>
		ReadOnly Friend Property Telefono1Column As DataColumn
			Get 
				Return _columnTelefono1 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field Telefono2</summary>
		ReadOnly Friend Property Telefono2Column As DataColumn
			Get 
				Return _columnTelefono2 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field CodTipoIscrizione</summary>
		ReadOnly Friend Property CodTipoIscrizioneColumn As DataColumn
			Get 
				Return _columnCodTipoIscrizione 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field CodFormaGiuridica</summary>
		ReadOnly Friend Property CodFormaGiuridicaColumn As DataColumn
			Get 
				Return _columnCodFormaGiuridica 
			End Get
		End Property

		''' <summary>Returns the column object belonging to the TypedList field UsatoPerSpedizione</summary>
		ReadOnly Friend Property UsatoPerSpedizioneColumn As DataColumn
			Get 
				Return _columnUsatoPerSpedizione 
			End Get
		End Property

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalColumnProperties
		' __LLBLGENPRO_USER_CODE_REGION_END

	' __LLBLGENPRO_USER_CODE_REGION_START CustomTypedListCode
	' __LLBLGENPRO_USER_CODE_REGION_END

	End Class

	''' <summary>
	''' Typed datarow for the typed datatable LstSoci
	''' </summary>
	Public Class LstSociRow 
		Inherits DataRow
		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfacesRow
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _parent As LstSociTypedList

		''' <summary>CTor</summary>
		''' <param name="rowBuilder">Row builder object to use when building this row</param>
		Protected Friend Sub New(rowBuilder As DataRowBuilder)
			MyBase.New(rowBuilder) 
			_parent = CType(Me.Table, LstSociTypedList)
		End Sub

		''' <summary>Gets / sets the value of the TypedList field AllegaBilancio<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.AllegaBilancio</remarks>
		Public Property [AllegaBilancio]() As System.Boolean
			Get 
				Return CType(If(IsAllegaBilancioNull(), TypeDefaultValue.GetDefaultValue(GetType(System.Boolean)), Me(_parent.AllegaBilancioColumn)), System.Boolean)
			End Get
			Set 
				Me(_parent.AllegaBilancioColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field AllegaBilancio is NULL, False otherwise.</summary>
		Public Function IsAllegaBilancioNull() As Boolean
			Return IsNull(_parent.AllegaBilancioColumn)
		End Function

		''' <summary>Sets the TypedList field AllegaBilancio to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetAllegaBilancioNull() 
			Me(_parent.AllegaBilancioColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Associazione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Associazione</remarks>
		Public Property [Associazione]() As System.String
			Get 
				Return CType(If(IsAssociazioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.AssociazioneColumn)), System.String)
			End Get
			Set 
				Me(_parent.AssociazioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Associazione is NULL, False otherwise.</summary>
		Public Function IsAssociazioneNull() As Boolean
			Return IsNull(_parent.AssociazioneColumn)
		End Function

		''' <summary>Sets the TypedList field Associazione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetAssociazioneNull() 
			Me(_parent.AssociazioneColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Cap<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Cap</remarks>
		Public Property [Cap]() As System.String
			Get 
				Return CType(If(IsCapNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CapColumn)), System.String)
			End Get
			Set 
				Me(_parent.CapColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Cap is NULL, False otherwise.</summary>
		Public Function IsCapNull() As Boolean
			Return IsNull(_parent.CapColumn)
		End Function

		''' <summary>Sets the TypedList field Cap to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCapNull() 
			Me(_parent.CapColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field CodCategoria<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.CodCategoria</remarks>
		Public Property [CodCategoria]() As System.String
			Get 
				Return CType(If(IsCodCategoriaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CodCategoriaColumn)), System.String)
			End Get
			Set 
				Me(_parent.CodCategoriaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field CodCategoria is NULL, False otherwise.</summary>
		Public Function IsCodCategoriaNull() As Boolean
			Return IsNull(_parent.CodCategoriaColumn)
		End Function

		''' <summary>Sets the TypedList field CodCategoria to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCodCategoriaNull() 
			Me(_parent.CodCategoriaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field CodiceFiscale<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.CodiceFiscale</remarks>
		Public Property [CodiceFiscale]() As System.String
			Get 
				Return CType(If(IsCodiceFiscaleNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CodiceFiscaleColumn)), System.String)
			End Get
			Set 
				Me(_parent.CodiceFiscaleColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field CodiceFiscale is NULL, False otherwise.</summary>
		Public Function IsCodiceFiscaleNull() As Boolean
			Return IsNull(_parent.CodiceFiscaleColumn)
		End Function

		''' <summary>Sets the TypedList field CodiceFiscale to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCodiceFiscaleNull() 
			Me(_parent.CodiceFiscaleColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field DataAdesione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.DataAdesione</remarks>
		Public Property [DataAdesione]() As System.DateTime
			Get 
				Return CType(If(IsDataAdesioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.DateTime)), Me(_parent.DataAdesioneColumn)), System.DateTime)
			End Get
			Set 
				Me(_parent.DataAdesioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field DataAdesione is NULL, False otherwise.</summary>
		Public Function IsDataAdesioneNull() As Boolean
			Return IsNull(_parent.DataAdesioneColumn)
		End Function

		''' <summary>Sets the TypedList field DataAdesione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetDataAdesioneNull() 
			Me(_parent.DataAdesioneColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field DataAssemblea<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.DataAssemblea</remarks>
		Public Property [DataAssemblea]() As System.DateTime
			Get 
				Return CType(If(IsDataAssembleaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.DateTime)), Me(_parent.DataAssembleaColumn)), System.DateTime)
			End Get
			Set 
				Me(_parent.DataAssembleaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field DataAssemblea is NULL, False otherwise.</summary>
		Public Function IsDataAssembleaNull() As Boolean
			Return IsNull(_parent.DataAssembleaColumn)
		End Function

		''' <summary>Sets the TypedList field DataAssemblea to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetDataAssembleaNull() 
			Me(_parent.DataAssembleaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field DataInizioAttivita<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.DataInizioAttivita</remarks>
		Public Property [DataInizioAttivita]() As System.DateTime
			Get 
				Return CType(If(IsDataInizioAttivitaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.DateTime)), Me(_parent.DataInizioAttivitaColumn)), System.DateTime)
			End Get
			Set 
				Me(_parent.DataInizioAttivitaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field DataInizioAttivita is NULL, False otherwise.</summary>
		Public Function IsDataInizioAttivitaNull() As Boolean
			Return IsNull(_parent.DataInizioAttivitaColumn)
		End Function

		''' <summary>Sets the TypedList field DataInizioAttivita to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetDataInizioAttivitaNull() 
			Me(_parent.DataInizioAttivitaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field DataPassaggioCda<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.DataPassaggioCda</remarks>
		Public Property [DataPassaggioCda]() As System.DateTime
			Get 
				Return CType(If(IsDataPassaggioCdaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.DateTime)), Me(_parent.DataPassaggioCdaColumn)), System.DateTime)
			End Get
			Set 
				Me(_parent.DataPassaggioCdaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field DataPassaggioCda is NULL, False otherwise.</summary>
		Public Function IsDataPassaggioCdaNull() As Boolean
			Return IsNull(_parent.DataPassaggioCdaColumn)
		End Function

		''' <summary>Sets the TypedList field DataPassaggioCda to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetDataPassaggioCdaNull() 
			Me(_parent.DataPassaggioCdaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field DataVersamentoUnaTantum<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.DataVersamentoUnaTantum</remarks>
		Public Property [DataVersamentoUnaTantum]() As System.DateTime
			Get 
				Return CType(If(IsDataVersamentoUnaTantumNull(), TypeDefaultValue.GetDefaultValue(GetType(System.DateTime)), Me(_parent.DataVersamentoUnaTantumColumn)), System.DateTime)
			End Get
			Set 
				Me(_parent.DataVersamentoUnaTantumColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field DataVersamentoUnaTantum is NULL, False otherwise.</summary>
		Public Function IsDataVersamentoUnaTantumNull() As Boolean
			Return IsNull(_parent.DataVersamentoUnaTantumColumn)
		End Function

		''' <summary>Sets the TypedList field DataVersamentoUnaTantum to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetDataVersamentoUnaTantumNull() 
			Me(_parent.DataVersamentoUnaTantumColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field DocumentazioneCciaa<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.DocumentazioneCciaa</remarks>
		Public Property [DocumentazioneCciaa]() As System.Boolean
			Get 
				Return CType(If(IsDocumentazioneCciaaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.Boolean)), Me(_parent.DocumentazioneCciaaColumn)), System.Boolean)
			End Get
			Set 
				Me(_parent.DocumentazioneCciaaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field DocumentazioneCciaa is NULL, False otherwise.</summary>
		Public Function IsDocumentazioneCciaaNull() As Boolean
			Return IsNull(_parent.DocumentazioneCciaaColumn)
		End Function

		''' <summary>Sets the TypedList field DocumentazioneCciaa to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetDocumentazioneCciaaNull() 
			Me(_parent.DocumentazioneCciaaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Email<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Email</remarks>
		Public Property [Email]() As System.String
			Get 
				Return CType(If(IsEmailNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.EmailColumn)), System.String)
			End Get
			Set 
				Me(_parent.EmailColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Email is NULL, False otherwise.</summary>
		Public Function IsEmailNull() As Boolean
			Return IsNull(_parent.EmailColumn)
		End Function

		''' <summary>Sets the TypedList field Email to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetEmailNull() 
			Me(_parent.EmailColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Fax<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Fax</remarks>
		Public Property [Fax]() As System.String
			Get 
				Return CType(If(IsFaxNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.FaxColumn)), System.String)
			End Get
			Set 
				Me(_parent.FaxColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Fax is NULL, False otherwise.</summary>
		Public Function IsFaxNull() As Boolean
			Return IsNull(_parent.FaxColumn)
		End Function

		''' <summary>Sets the TypedList field Fax to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetFaxNull() 
			Me(_parent.FaxColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Id<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Id</remarks>
		Public Property [Id]() As System.Int32
			Get 
				Return CType(If(IsIdNull(), TypeDefaultValue.GetDefaultValue(GetType(System.Int32)), Me(_parent.IdColumn)), System.Int32)
			End Get
			Set 
				Me(_parent.IdColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Id is NULL, False otherwise.</summary>
		Public Function IsIdNull() As Boolean
			Return IsNull(_parent.IdColumn)
		End Function

		''' <summary>Sets the TypedList field Id to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetIdNull() 
			Me(_parent.IdColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Indirizzo<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Indirizzo</remarks>
		Public Property [Indirizzo]() As System.String
			Get 
				Return CType(If(IsIndirizzoNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.IndirizzoColumn)), System.String)
			End Get
			Set 
				Me(_parent.IndirizzoColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Indirizzo is NULL, False otherwise.</summary>
		Public Function IsIndirizzoNull() As Boolean
			Return IsNull(_parent.IndirizzoColumn)
		End Function

		''' <summary>Sets the TypedList field Indirizzo to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetIndirizzoNull() 
			Me(_parent.IndirizzoColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field CodInfoStato<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.CodInfoStato</remarks>
		Public Property [CodInfoStato]() As System.String
			Get 
				Return CType(If(IsCodInfoStatoNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CodInfoStatoColumn)), System.String)
			End Get
			Set 
				Me(_parent.CodInfoStatoColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field CodInfoStato is NULL, False otherwise.</summary>
		Public Function IsCodInfoStatoNull() As Boolean
			Return IsNull(_parent.CodInfoStatoColumn)
		End Function

		''' <summary>Sets the TypedList field CodInfoStato to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCodInfoStatoNull() 
			Me(_parent.CodInfoStatoColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field LegaleRappresentante<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.LegaleRappresentante</remarks>
		Public Property [LegaleRappresentante]() As System.String
			Get 
				Return CType(If(IsLegaleRappresentanteNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.LegaleRappresentanteColumn)), System.String)
			End Get
			Set 
				Me(_parent.LegaleRappresentanteColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field LegaleRappresentante is NULL, False otherwise.</summary>
		Public Function IsLegaleRappresentanteNull() As Boolean
			Return IsNull(_parent.LegaleRappresentanteColumn)
		End Function

		''' <summary>Sets the TypedList field LegaleRappresentante to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetLegaleRappresentanteNull() 
			Me(_parent.LegaleRappresentanteColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Localita<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Localita</remarks>
		Public Property [Localita]() As System.String
			Get 
				Return CType(If(IsLocalitaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.LocalitaColumn)), System.String)
			End Get
			Set 
				Me(_parent.LocalitaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Localita is NULL, False otherwise.</summary>
		Public Function IsLocalitaNull() As Boolean
			Return IsNull(_parent.LocalitaColumn)
		End Function

		''' <summary>Sets the TypedList field Localita to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetLocalitaNull() 
			Me(_parent.LocalitaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field PartitaIva<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.PartitaIva</remarks>
		Public Property [PartitaIva]() As System.String
			Get 
				Return CType(If(IsPartitaIvaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.PartitaIvaColumn)), System.String)
			End Get
			Set 
				Me(_parent.PartitaIvaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field PartitaIva is NULL, False otherwise.</summary>
		Public Function IsPartitaIvaNull() As Boolean
			Return IsNull(_parent.PartitaIvaColumn)
		End Function

		''' <summary>Sets the TypedList field PartitaIva to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetPartitaIvaNull() 
			Me(_parent.PartitaIvaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Provincia<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Provincia</remarks>
		Public Property [Provincia]() As System.String
			Get 
				Return CType(If(IsProvinciaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.ProvinciaColumn)), System.String)
			End Get
			Set 
				Me(_parent.ProvinciaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Provincia is NULL, False otherwise.</summary>
		Public Function IsProvinciaNull() As Boolean
			Return IsNull(_parent.ProvinciaColumn)
		End Function

		''' <summary>Sets the TypedList field Provincia to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetProvinciaNull() 
			Me(_parent.ProvinciaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field QuotaAdesione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.QuotaAdesione</remarks>
		Public Property [QuotaAdesione]() As System.Decimal
			Get 
				Return CType(If(IsQuotaAdesioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.Decimal)), Me(_parent.QuotaAdesioneColumn)), System.Decimal)
			End Get
			Set 
				Me(_parent.QuotaAdesioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field QuotaAdesione is NULL, False otherwise.</summary>
		Public Function IsQuotaAdesioneNull() As Boolean
			Return IsNull(_parent.QuotaAdesioneColumn)
		End Function

		''' <summary>Sets the TypedList field QuotaAdesione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetQuotaAdesioneNull() 
			Me(_parent.QuotaAdesioneColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field RagioneSociale<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.RagioneSociale</remarks>
		Public Property [RagioneSociale]() As System.String
			Get 
				Return CType(If(IsRagioneSocialeNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.RagioneSocialeColumn)), System.String)
			End Get
			Set 
				Me(_parent.RagioneSocialeColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field RagioneSociale is NULL, False otherwise.</summary>
		Public Function IsRagioneSocialeNull() As Boolean
			Return IsNull(_parent.RagioneSocialeColumn)
		End Function

		''' <summary>Sets the TypedList field RagioneSociale to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetRagioneSocialeNull() 
			Me(_parent.RagioneSocialeColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Regione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Regione</remarks>
		Public Property [Regione]() As System.String
			Get 
				Return CType(If(IsRegioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.RegioneColumn)), System.String)
			End Get
			Set 
				Me(_parent.RegioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Regione is NULL, False otherwise.</summary>
		Public Function IsRegioneNull() As Boolean
			Return IsNull(_parent.RegioneColumn)
		End Function

		''' <summary>Sets the TypedList field Regione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetRegioneNull() 
			Me(_parent.RegioneColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field CodStato<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.CodStato</remarks>
		Public Property [CodStato]() As System.String
			Get 
				Return CType(If(IsCodStatoNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CodStatoColumn)), System.String)
			End Get
			Set 
				Me(_parent.CodStatoColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field CodStato is NULL, False otherwise.</summary>
		Public Function IsCodStatoNull() As Boolean
			Return IsNull(_parent.CodStatoColumn)
		End Function

		''' <summary>Sets the TypedList field CodStato to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCodStatoNull() 
			Me(_parent.CodStatoColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field StatoDichiarazione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.StatoDichiarazione</remarks>
		Public Property [StatoDichiarazione]() As System.String
			Get 
				Return CType(If(IsStatoDichiarazioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.StatoDichiarazioneColumn)), System.String)
			End Get
			Set 
				Me(_parent.StatoDichiarazioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field StatoDichiarazione is NULL, False otherwise.</summary>
		Public Function IsStatoDichiarazioneNull() As Boolean
			Return IsNull(_parent.StatoDichiarazioneColumn)
		End Function

		''' <summary>Sets the TypedList field StatoDichiarazione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetStatoDichiarazioneNull() 
			Me(_parent.StatoDichiarazioneColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field StatoPagamenti<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.StatoPagamenti</remarks>
		Public Property [StatoPagamenti]() As System.String
			Get 
				Return CType(If(IsStatoPagamentiNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.StatoPagamentiColumn)), System.String)
			End Get
			Set 
				Me(_parent.StatoPagamentiColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field StatoPagamenti is NULL, False otherwise.</summary>
		Public Function IsStatoPagamentiNull() As Boolean
			Return IsNull(_parent.StatoPagamentiColumn)
		End Function

		''' <summary>Sets the TypedList field StatoPagamenti to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetStatoPagamentiNull() 
			Me(_parent.StatoPagamentiColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Telefono1<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Telefono1</remarks>
		Public Property [Telefono1]() As System.String
			Get 
				Return CType(If(IsTelefono1Null(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.Telefono1Column)), System.String)
			End Get
			Set 
				Me(_parent.Telefono1Column) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Telefono1 is NULL, False otherwise.</summary>
		Public Function IsTelefono1Null() As Boolean
			Return IsNull(_parent.Telefono1Column)
		End Function

		''' <summary>Sets the TypedList field Telefono1 to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetTelefono1Null() 
			Me(_parent.Telefono1Column) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field Telefono2<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.Telefono2</remarks>
		Public Property [Telefono2]() As System.String
			Get 
				Return CType(If(IsTelefono2Null(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.Telefono2Column)), System.String)
			End Get
			Set 
				Me(_parent.Telefono2Column) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field Telefono2 is NULL, False otherwise.</summary>
		Public Function IsTelefono2Null() As Boolean
			Return IsNull(_parent.Telefono2Column)
		End Function

		''' <summary>Sets the TypedList field Telefono2 to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetTelefono2Null() 
			Me(_parent.Telefono2Column) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field CodTipoIscrizione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.CodTipoIscrizione</remarks>
		Public Property [CodTipoIscrizione]() As System.String
			Get 
				Return CType(If(IsCodTipoIscrizioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CodTipoIscrizioneColumn)), System.String)
			End Get
			Set 
				Me(_parent.CodTipoIscrizioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field CodTipoIscrizione is NULL, False otherwise.</summary>
		Public Function IsCodTipoIscrizioneNull() As Boolean
			Return IsNull(_parent.CodTipoIscrizioneColumn)
		End Function

		''' <summary>Sets the TypedList field CodTipoIscrizione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCodTipoIscrizioneNull() 
			Me(_parent.CodTipoIscrizioneColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field CodFormaGiuridica<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.CodFormaGiuridica</remarks>
		Public Property [CodFormaGiuridica]() As System.String
			Get 
				Return CType(If(IsCodFormaGiuridicaNull(), TypeDefaultValue.GetDefaultValue(GetType(System.String)), Me(_parent.CodFormaGiuridicaColumn)), System.String)
			End Get
			Set 
				Me(_parent.CodFormaGiuridicaColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field CodFormaGiuridica is NULL, False otherwise.</summary>
		Public Function IsCodFormaGiuridicaNull() As Boolean
			Return IsNull(_parent.CodFormaGiuridicaColumn)
		End Function

		''' <summary>Sets the TypedList field CodFormaGiuridica to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetCodFormaGiuridicaNull() 
			Me(_parent.CodFormaGiuridicaColumn) = System.Convert.DBNull
		End Sub
		''' <summary>Gets / sets the value of the TypedList field UsatoPerSpedizione<br/><br/></summary>
		''' <remarks>Mapped On: Azienda.UsatoPerSpedizione</remarks>
		Public Property [UsatoPerSpedizione]() As System.Boolean
			Get 
				Return CType(If(IsUsatoPerSpedizioneNull(), TypeDefaultValue.GetDefaultValue(GetType(System.Boolean)), Me(_parent.UsatoPerSpedizioneColumn)), System.Boolean)
			End Get
			Set 
				Me(_parent.UsatoPerSpedizioneColumn) = Value
			End Set
		End Property

		''' <summary>Returns True if the TypedList field UsatoPerSpedizione is NULL, False otherwise.</summary>
		Public Function IsUsatoPerSpedizioneNull() As Boolean
			Return IsNull(_parent.UsatoPerSpedizioneColumn)
		End Function

		''' <summary>Sets the TypedList field UsatoPerSpedizione to NULL. Not recommended a typed list should be used as a readonly Object.</summary>
		Public Sub SetUsatoPerSpedizioneNull() 
			Me(_parent.UsatoPerSpedizioneColumn) = System.Convert.DBNull
		End Sub


	' __LLBLGENPRO_USER_CODE_REGION_START CustomTypedListRowCode
	' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace
