' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Audit'.<br/><br/></summary>
	<Serializable()> _
	Public Class AuditEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New AuditEntityStaticMetaData()
		Private Shared _relationsFactory As New AuditRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class AuditEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("AuditEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.AuditEntity), GetType(AuditEntity), GetType(AuditEntityFactory), False)
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this AuditEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for Audit which data should be fetched into this Audit object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for Audit which data should be fetched into this Audit object</param>
		''' <param name="validator">The custom validator object for this AuditEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this AuditEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As AuditRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>The Data property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."data".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Data]() As System.DateTime
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Data), True), System.DateTime)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Data), value)
			End Set
		End Property

		''' <summary>The Dati property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."dati".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Dati]() As System.String
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Dati), True), System.String)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Dati), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The Ip property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."ip".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Ip]() As System.String
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Ip), True), System.String)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Ip), value)
			End Set
		End Property

		''' <summary>The Operazione property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."operazione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Operazione]() As System.String
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Operazione), True), System.String)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Operazione), value)
			End Set
		End Property

		''' <summary>The Target property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."target".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Target]() As System.String
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Target), True), System.String)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Target), value)
			End Set
		End Property

		''' <summary>The Username property of the Entity Audit<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Audit"."username".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Username]() As System.String
			Get
				Return CType(GetValue(CInt(AuditFieldIndex.Username), True), System.String)
			End Get
			Set
				SetValue(CInt(AuditFieldIndex.Username), value)
			End Set
		End Property





		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Audit.</summary>
	Public Enum AuditFieldIndex
		[Data]
		[Dati]
		[Id]
		[Ip]
		[Operazione]
		[Target]
		[Username]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Audit.</summary>
	Public Class AuditRelations



	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticAuditRelations

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
