' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Azienda'.<br/><br/></summary>
	<Serializable()> _
	Public Class AziendaEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _aziendaAllegato As EntityCollection(Of AziendaAllegatoEntity)
		Private _attivita As EntityCollection(Of AttivitaEntity)
		Private _aziendaProdotti As EntityCollection(Of AziendaProdottoEntity)
		Private _contatti As EntityCollection(Of ContattoEntity)
		Private _dichiarazioni As EntityCollection(Of DichiarazioneEntity)
		Private _dichiarazioneOnLines As EntityCollection(Of DichiarazioneOnLineEntity)
		Private _eventi As EntityCollection(Of EventoAziendaEntity)
		Private _licenze As EntityCollection(Of LicenzaAziendaEntity)
		Private _sedi As EntityCollection(Of SedeEntity)
		Private _categoria As CategoriaEntity
		Private _formaGiuridica As FormaGiuridicaEntity
		Private _infoStato As InfoStatoEntity
		Private _statoSocio As StatoSocioEntity
		Private _tipoSocio As TipoSocioEntity
		Private _allegatos As AllegatoEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New AziendaEntityStaticMetaData()
		Private Shared _relationsFactory As New AziendaRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Categoria</summary>
			Public Shared ReadOnly [Categoria] As String = "Categoria"
			''' <summary>Member name FormaGiuridica</summary>
			Public Shared ReadOnly [FormaGiuridica] As String = "FormaGiuridica"
			''' <summary>Member name InfoStato</summary>
			Public Shared ReadOnly [InfoStato] As String = "InfoStato"
			''' <summary>Member name StatoSocio</summary>
			Public Shared ReadOnly [StatoSocio] As String = "StatoSocio"
			''' <summary>Member name TipoSocio</summary>
			Public Shared ReadOnly [TipoSocio] As String = "TipoSocio"
			''' <summary>Member name AziendaAllegato</summary>
			Public Shared ReadOnly [AziendaAllegato] As String  = "AziendaAllegato"
			''' <summary>Member name Attivita</summary>
			Public Shared ReadOnly [Attivita] As String  = "Attivita"
			''' <summary>Member name AziendaProdotti</summary>
			Public Shared ReadOnly [AziendaProdotti] As String  = "AziendaProdotti"
			''' <summary>Member name Contatti</summary>
			Public Shared ReadOnly [Contatti] As String  = "Contatti"
			''' <summary>Member name Dichiarazioni</summary>
			Public Shared ReadOnly [Dichiarazioni] As String  = "Dichiarazioni"
			''' <summary>Member name DichiarazioneOnLines</summary>
			Public Shared ReadOnly [DichiarazioneOnLines] As String  = "DichiarazioneOnLines"
			''' <summary>Member name Eventi</summary>
			Public Shared ReadOnly [Eventi] As String  = "Eventi"
			''' <summary>Member name Licenze</summary>
			Public Shared ReadOnly [Licenze] As String  = "Licenze"
			''' <summary>Member name Sedi</summary>
			Public Shared ReadOnly [Sedi] As String  = "Sedi"
			''' <summary>Member name Allegatos</summary>
			Public Shared ReadOnly [Allegatos] As String  = "Allegatos"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class AziendaEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("AziendaEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.AziendaEntity), GetType(AziendaEntity), GetType(AziendaEntityFactory), False)
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of AziendaAllegatoEntity))("AziendaAllegato", Function(a) a._aziendaAllegato, Sub(a, b) a._aziendaAllegato = b, Function(a) a.AziendaAllegato, Function() New AziendaRelations().AziendaAllegatoEntityUsingIdSocio, GetType(AziendaAllegatoEntity), CInt(DAL.EntityType.AziendaAllegatoEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of AttivitaEntity))("Attivita", Function(a) a._attivita, Sub(a, b) a._attivita = b, Function(a) a.Attivita, Function() New AziendaRelations().AttivitaEntityUsingIdAzienda, GetType(AttivitaEntity), CInt(DAL.EntityType.AttivitaEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of AziendaProdottoEntity))("AziendaProdotti", Function(a) a._aziendaProdotti, Sub(a, b) a._aziendaProdotti = b, Function(a) a.AziendaProdotti, Function() New AziendaRelations().AziendaProdottoEntityUsingIdAzienda, GetType(AziendaProdottoEntity), CInt(DAL.EntityType.AziendaProdottoEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of ContattoEntity))("Contatti", Function(a) a._contatti, Sub(a, b) a._contatti = b, Function(a) a.Contatti, Function() New AziendaRelations().ContattoEntityUsingIdAzienda, GetType(ContattoEntity), CInt(DAL.EntityType.ContattoEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of DichiarazioneEntity))("Dichiarazioni", Function(a) a._dichiarazioni, Sub(a, b) a._dichiarazioni = b, Function(a) a.Dichiarazioni, Function() New AziendaRelations().DichiarazioneEntityUsingIdAzienda, GetType(DichiarazioneEntity), CInt(DAL.EntityType.DichiarazioneEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of DichiarazioneOnLineEntity))("DichiarazioneOnLines", Function(a) a._dichiarazioneOnLines, Sub(a, b) a._dichiarazioneOnLines = b, Function(a) a.DichiarazioneOnLines, Function() New AziendaRelations().DichiarazioneOnLineEntityUsingIdAzienda, GetType(DichiarazioneOnLineEntity), CInt(DAL.EntityType.DichiarazioneOnLineEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of EventoAziendaEntity))("Eventi", Function(a) a._eventi, Sub(a, b) a._eventi = b, Function(a) a.Eventi, Function() New AziendaRelations().EventoAziendaEntityUsingIdAzienda, GetType(EventoAziendaEntity), CInt(DAL.EntityType.EventoAziendaEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of LicenzaAziendaEntity))("Licenze", Function(a) a._licenze, Sub(a, b) a._licenze = b, Function(a) a.Licenze, Function() New AziendaRelations().LicenzaAziendaEntityUsingIdAzienda, GetType(LicenzaAziendaEntity), CInt(DAL.EntityType.LicenzaAziendaEntity))
				AddNavigatorMetaData(Of AziendaEntity, EntityCollection(Of SedeEntity))("Sedi", Function(a) a._sedi, Sub(a, b) a._sedi = b, Function(a) a.Sedi, Function() New AziendaRelations().SedeEntityUsingIdAzienda, GetType(SedeEntity), CInt(DAL.EntityType.SedeEntity))
				AddNavigatorMetaData(Of AziendaEntity, CategoriaEntity)("Categoria", "Aziende", Sub(a, b) a._categoria = b, Function(a) a._categoria, Sub(a, b) a.Categoria = b, DAL.RelationClasses.StaticAziendaRelations.CategoriaEntityUsingCodCategoriaStatic, Function() New AziendaRelations().CategoriaEntityUsingCodCategoria, Nothing, New Integer() { CInt(AziendaFieldIndex.CodCategoria) }, Nothing, True, CInt(DAL.EntityType.CategoriaEntity))
				AddNavigatorMetaData(Of AziendaEntity, FormaGiuridicaEntity)("FormaGiuridica", "Aziende", Sub(a, b) a._formaGiuridica = b, Function(a) a._formaGiuridica, Sub(a, b) a.FormaGiuridica = b, DAL.RelationClasses.StaticAziendaRelations.FormaGiuridicaEntityUsingCodFormaGiuridicaStatic, Function() New AziendaRelations().FormaGiuridicaEntityUsingCodFormaGiuridica, Nothing, New Integer() { CInt(AziendaFieldIndex.CodFormaGiuridica) }, Nothing, True, CInt(DAL.EntityType.FormaGiuridicaEntity))
				AddNavigatorMetaData(Of AziendaEntity, InfoStatoEntity)("InfoStato", "Aziende", Sub(a, b) a._infoStato = b, Function(a) a._infoStato, Sub(a, b) a.InfoStato = b, DAL.RelationClasses.StaticAziendaRelations.InfoStatoEntityUsingCodInfoStatoStatic, Function() New AziendaRelations().InfoStatoEntityUsingCodInfoStato, Nothing, New Integer() { CInt(AziendaFieldIndex.CodInfoStato) }, Nothing, True, CInt(DAL.EntityType.InfoStatoEntity))
				AddNavigatorMetaData(Of AziendaEntity, StatoSocioEntity)("StatoSocio", "Aziende", Sub(a, b) a._statoSocio = b, Function(a) a._statoSocio, Sub(a, b) a.StatoSocio = b, DAL.RelationClasses.StaticAziendaRelations.StatoSocioEntityUsingCodStatoStatic, Function() New AziendaRelations().StatoSocioEntityUsingCodStato, Nothing, New Integer() { CInt(AziendaFieldIndex.CodStato) }, Nothing, True, CInt(DAL.EntityType.StatoSocioEntity))
				AddNavigatorMetaData(Of AziendaEntity, TipoSocioEntity)("TipoSocio", "Aziende", Sub(a, b) a._tipoSocio = b, Function(a) a._tipoSocio, Sub(a, b) a.TipoSocio = b, DAL.RelationClasses.StaticAziendaRelations.TipoSocioEntityUsingCodTipoIscrizioneStatic, Function() New AziendaRelations().TipoSocioEntityUsingCodTipoIscrizione, Nothing, New Integer() { CInt(AziendaFieldIndex.CodTipoIscrizione) }, Nothing, True, CInt(DAL.EntityType.TipoSocioEntity))
				AddNavigatorMetaData(Of AziendaEntity, AllegatoEntity)("Allegatos", "Azienda", Sub(a, b) a._allegatos = b, Function(a) a._allegatos, Sub(a, b) a.Allegatos = b, DAL.RelationClasses.StaticAziendaRelations.AllegatoEntityUsingIdAziendaStatic, Function() New AziendaRelations().AllegatoEntityUsingIdAzienda, Nothing, Nothing, Nothing, True, CInt(DAL.EntityType.AllegatoEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this AziendaEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for Azienda which data should be fetched into this Azienda object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for Azienda which data should be fetched into this Azienda object</param>
		''' <param name="validator">The custom validator object for this AziendaEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AziendaAllegato' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoAziendaAllegato() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("AziendaAllegato")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Attivita' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoAttivita() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Attivita")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AziendaProdotto' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoAziendaProdotti() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("AziendaProdotti")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Contatto' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoContatti() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Contatti")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Dichiarazione' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoDichiarazioni() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Dichiarazioni")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'DichiarazioneOnLine' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoDichiarazioneOnLines() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("DichiarazioneOnLines")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'EventoAzienda' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoEventi() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Eventi")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'LicenzaAzienda' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoLicenze() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Licenze")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Sede' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoSedi() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Sedi")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Categoria' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoCategoria() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Categoria")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'FormaGiuridica' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoFormaGiuridica() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("FormaGiuridica")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'InfoStato' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoInfoStato() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("InfoStato")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'StatoSocio' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoStatoSocio() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("StatoSocio")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'TipoSocio' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoTipoSocio() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("TipoSocio")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Allegato' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoAllegatos() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Allegatos")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this AziendaEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As AziendaRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AziendaAllegato'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathAziendaAllegato() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("AziendaAllegato", CommonEntityBase.CreateEntityCollection(Of AziendaAllegatoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Attivita'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathAttivita() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Attivita", CommonEntityBase.CreateEntityCollection(Of AttivitaEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AziendaProdotto'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathAziendaProdotti() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("AziendaProdotti", CommonEntityBase.CreateEntityCollection(Of AziendaProdottoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Contatto'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathContatti() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Contatti", CommonEntityBase.CreateEntityCollection(Of ContattoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Dichiarazione'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathDichiarazioni() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Dichiarazioni", CommonEntityBase.CreateEntityCollection(Of DichiarazioneEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'DichiarazioneOnLine'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathDichiarazioneOnLines() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("DichiarazioneOnLines", CommonEntityBase.CreateEntityCollection(Of DichiarazioneOnLineEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'EventoAzienda'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathEventi() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Eventi", CommonEntityBase.CreateEntityCollection(Of EventoAziendaEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'LicenzaAzienda'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathLicenze() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Licenze", CommonEntityBase.CreateEntityCollection(Of LicenzaAziendaEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Sede'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathSedi() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Sedi", CommonEntityBase.CreateEntityCollection(Of SedeEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Categoria' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathCategoria() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Categoria", CommonEntityBase.CreateEntityCollection(Of CategoriaEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'FormaGiuridica' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathFormaGiuridica() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("FormaGiuridica", CommonEntityBase.CreateEntityCollection(Of FormaGiuridicaEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'InfoStato' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathInfoStato() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("InfoStato", CommonEntityBase.CreateEntityCollection(Of InfoStatoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'StatoSocio' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathStatoSocio() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("StatoSocio", CommonEntityBase.CreateEntityCollection(Of StatoSocioEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'TipoSocio' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathTipoSocio() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("TipoSocio", CommonEntityBase.CreateEntityCollection(Of TipoSocioEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Allegato'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathAllegatos() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Allegatos", CommonEntityBase.CreateEntityCollection(Of AllegatoEntity)())
			End Get
		End Property

		''' <summary>The AllegaBilancio property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."AllegaBilancio".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [AllegaBilancio]() As System.Boolean
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.AllegaBilancio), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.AllegaBilancio), value)
			End Set
		End Property

		''' <summary>The Associazione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Associazione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Associazione]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Associazione), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Associazione), value)
			End Set
		End Property

		''' <summary>The Cap property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Cap".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 5.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Cap]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Cap), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Cap), value)
			End Set
		End Property

		''' <summary>The CodCategoria property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."CodCategoria".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodCategoria]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.CodCategoria), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.CodCategoria), value)
			End Set
		End Property

		''' <summary>The CodFormaGiuridica property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."CodFormaGiuridica".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodFormaGiuridica]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.CodFormaGiuridica), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.CodFormaGiuridica), value)
			End Set
		End Property

		''' <summary>The CodiceFiscale property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."CodiceFiscale".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 16.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodiceFiscale]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.CodiceFiscale), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.CodiceFiscale), value)
			End Set
		End Property

		''' <summary>The CodInfoStato property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."CodInfoStato".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodInfoStato]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.CodInfoStato), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.CodInfoStato), value)
			End Set
		End Property

		''' <summary>The CodStato property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."CodStato".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodStato]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.CodStato), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.CodStato), value)
			End Set
		End Property

		''' <summary>The CodTipoIscrizione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."CodTipoIscrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodTipoIscrizione]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.CodTipoIscrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.CodTipoIscrizione), value)
			End Set
		End Property

		''' <summary>The DataAdesione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."DataAdesione".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataAdesione]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.DataAdesione), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.DataAdesione), value)
			End Set
		End Property

		''' <summary>The DataAssemblea property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."DataAssemblea".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataAssemblea]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.DataAssemblea), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.DataAssemblea), value)
			End Set
		End Property

		''' <summary>The DataInizioAttivita property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."DataInizioAttivita".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataInizioAttivita]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.DataInizioAttivita), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.DataInizioAttivita), value)
			End Set
		End Property

		''' <summary>The DataPassaggioCda property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."DataPassaggioCDA".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataPassaggioCda]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.DataPassaggioCda), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.DataPassaggioCda), value)
			End Set
		End Property

		''' <summary>The DataVersamentoUnaTantum property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."DataVersamentoUnaTantum".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataVersamentoUnaTantum]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.DataVersamentoUnaTantum), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.DataVersamentoUnaTantum), value)
			End Set
		End Property

		''' <summary>The DocumentazioneCciaa property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."DocumentazioneCCIAA".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [DocumentazioneCciaa]() As System.Boolean
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.DocumentazioneCciaa), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.DocumentazioneCciaa), value)
			End Set
		End Property

		''' <summary>The Email property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Email".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Email]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Email), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Email), value)
			End Set
		End Property

		''' <summary>The Fax property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Fax".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Fax]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Fax), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Fax), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The Indirizzo property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Indirizzo".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Indirizzo]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Indirizzo), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Indirizzo), value)
			End Set
		End Property

		''' <summary>The LegaleRappresentante property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."LegaleRappresentante".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [LegaleRappresentante]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.LegaleRappresentante), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.LegaleRappresentante), value)
			End Set
		End Property

		''' <summary>The Localita property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Localita".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Localita]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Localita), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Localita), value)
			End Set
		End Property

		''' <summary>The PartitaIva property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."PartitaIVA".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 16.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [PartitaIva]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.PartitaIva), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.PartitaIva), value)
			End Set
		End Property

		''' <summary>The Pec property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Pec".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Pec]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Pec), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Pec), value)
			End Set
		End Property

		''' <summary>The Provincia property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Provincia".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 5.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Provincia]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Provincia), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Provincia), value)
			End Set
		End Property

		''' <summary>The QuotaAdesione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."QuotaAdesione".<br/>Table field type characteristics (type, precision, scale, length): Money, 19, 4, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [QuotaAdesione]() As Nullable(Of System.Decimal)
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.QuotaAdesione), False), Nullable(Of System.Decimal))
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.QuotaAdesione), value)
			End Set
		End Property

		''' <summary>The RagioneSociale property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."RagioneSociale".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [RagioneSociale]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.RagioneSociale), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.RagioneSociale), value)
			End Set
		End Property

		''' <summary>The RagSocPrecedenti property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."RagSocPrecedenti".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 4000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [RagSocPrecedenti]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.RagSocPrecedenti), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.RagSocPrecedenti), value)
			End Set
		End Property

		''' <summary>The Regione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Regione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Regione]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Regione), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Regione), value)
			End Set
		End Property

		''' <summary>The SitoWeb property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."SitoWeb".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [SitoWeb]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.SitoWeb), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.SitoWeb), value)
			End Set
		End Property

		''' <summary>The StatoDichiarazione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."StatoDichiarazione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [StatoDichiarazione]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.StatoDichiarazione), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.StatoDichiarazione), value)
			End Set
		End Property

		''' <summary>The StatoPagamenti property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."StatoPagamenti".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [StatoPagamenti]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.StatoPagamenti), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.StatoPagamenti), value)
			End Set
		End Property

		''' <summary>The Telefono1 property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Telefono1".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Telefono1]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Telefono1), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Telefono1), value)
			End Set
		End Property

		''' <summary>The Telefono2 property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."Telefono2".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Telefono2]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.Telefono2), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.Telefono2), value)
			End Set
		End Property

		''' <summary>The UsatoPerSpedizione property of the Entity Azienda<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Azienda"."UsatoPerSpedizione".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [UsatoPerSpedizione]() As System.Boolean
			Get
				Return CType(GetValue(CInt(AziendaFieldIndex.UsatoPerSpedizione), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(AziendaFieldIndex.UsatoPerSpedizione), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'AziendaAllegatoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(AziendaAllegatoEntity))> _
		Public Overridable ReadOnly Property [AziendaAllegato]() As EntityCollection(Of AziendaAllegatoEntity)
			Get
				Return GetOrCreateEntityCollection(Of AziendaAllegatoEntity, AziendaAllegatoEntityFactory)("Azienda", true, false, _aziendaAllegato)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'AttivitaEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(AttivitaEntity))> _
		Public Overridable ReadOnly Property [Attivita]() As EntityCollection(Of AttivitaEntity)
			Get
				Return GetOrCreateEntityCollection(Of AttivitaEntity, AttivitaEntityFactory)("Azienda", true, false, _attivita)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'AziendaProdottoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(AziendaProdottoEntity))> _
		Public Overridable ReadOnly Property [AziendaProdotti]() As EntityCollection(Of AziendaProdottoEntity)
			Get
				Return GetOrCreateEntityCollection(Of AziendaProdottoEntity, AziendaProdottoEntityFactory)("Azienda", true, false, _aziendaProdotti)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'ContattoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(ContattoEntity))> _
		Public Overridable ReadOnly Property [Contatti]() As EntityCollection(Of ContattoEntity)
			Get
				Return GetOrCreateEntityCollection(Of ContattoEntity, ContattoEntityFactory)("Azienda", true, false, _contatti)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'DichiarazioneEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(DichiarazioneEntity))> _
		Public Overridable ReadOnly Property [Dichiarazioni]() As EntityCollection(Of DichiarazioneEntity)
			Get
				Return GetOrCreateEntityCollection(Of DichiarazioneEntity, DichiarazioneEntityFactory)("Azienda", true, false, _dichiarazioni)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'DichiarazioneOnLineEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(DichiarazioneOnLineEntity))> _
		Public Overridable ReadOnly Property [DichiarazioneOnLines]() As EntityCollection(Of DichiarazioneOnLineEntity)
			Get
				Return GetOrCreateEntityCollection(Of DichiarazioneOnLineEntity, DichiarazioneOnLineEntityFactory)("Azienda", true, false, _dichiarazioneOnLines)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'EventoAziendaEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(EventoAziendaEntity))> _
		Public Overridable ReadOnly Property [Eventi]() As EntityCollection(Of EventoAziendaEntity)
			Get
				Return GetOrCreateEntityCollection(Of EventoAziendaEntity, EventoAziendaEntityFactory)("Azienda", true, false, _eventi)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'LicenzaAziendaEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(LicenzaAziendaEntity))> _
		Public Overridable ReadOnly Property [Licenze]() As EntityCollection(Of LicenzaAziendaEntity)
			Get
				Return GetOrCreateEntityCollection(Of LicenzaAziendaEntity, LicenzaAziendaEntityFactory)("Azienda", true, false, _licenze)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'SedeEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(SedeEntity))> _
		Public Overridable ReadOnly Property [Sedi]() As EntityCollection(Of SedeEntity)
			Get
				Return GetOrCreateEntityCollection(Of SedeEntity, SedeEntityFactory)("Azienda", true, false, _sedi)
			End Get
		End Property


		''' <summary>Gets / sets related entity of type 'CategoriaEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Categoria]() As CategoriaEntity
			Get
				Return _categoria
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Categoria") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'FormaGiuridicaEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [FormaGiuridica]() As FormaGiuridicaEntity
			Get
				Return _formaGiuridica
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "FormaGiuridica") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'InfoStatoEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [InfoStato]() As InfoStatoEntity
			Get
				Return _infoStato
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "InfoStato") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'StatoSocioEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [StatoSocio]() As StatoSocioEntity
			Get
				Return _statoSocio
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "StatoSocio") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'TipoSocioEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [TipoSocio]() As TipoSocioEntity
			Get
				Return _tipoSocio
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "TipoSocio") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'AllegatoEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Allegatos]() As AllegatoEntity
			Get
				Return _allegatos
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Allegatos") 
			End Set
		End Property

		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Azienda.</summary>
	Public Enum AziendaFieldIndex
		[AllegaBilancio]
		[Associazione]
		[Cap]
		[CodCategoria]
		[CodFormaGiuridica]
		[CodiceFiscale]
		[CodInfoStato]
		[CodStato]
		[CodTipoIscrizione]
		[DataAdesione]
		[DataAssemblea]
		[DataInizioAttivita]
		[DataPassaggioCda]
		[DataVersamentoUnaTantum]
		[DocumentazioneCciaa]
		[Email]
		[Fax]
		[Id]
		[Indirizzo]
		[LegaleRappresentante]
		[Localita]
		[PartitaIva]
		[Pec]
		[Provincia]
		[QuotaAdesione]
		[RagioneSociale]
		[RagSocPrecedenti]
		[Regione]
		[SitoWeb]
		[StatoDichiarazione]
		[StatoPagamenti]
		[Telefono1]
		[Telefono2]
		[UsatoPerSpedizione]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Azienda.</summary>
	Public Class AziendaRelations

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and AziendaAllegatoEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - AziendaAllegato.IdSocio
		''' </summary>
		Public Overridable ReadOnly Property AziendaAllegatoEntityUsingIdSocio() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AziendaAllegato", True, { AziendaFields.Id, AziendaAllegatoFields.IdSocio })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and AttivitaEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - Attivita.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property AttivitaEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Attivita", True, { AziendaFields.Id, AttivitaFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and AziendaProdottoEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - AziendaProdotto.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property AziendaProdottoEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AziendaProdotti", True, { AziendaFields.Id, AziendaProdottoFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and ContattoEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - Contatto.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property ContattoEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Contatti", True, { AziendaFields.Id, ContattoFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and DichiarazioneEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - Dichiarazione.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property DichiarazioneEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Dichiarazioni", True, { AziendaFields.Id, DichiarazioneFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and DichiarazioneOnLineEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - DichiarazioneOnLine.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property DichiarazioneOnLineEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "DichiarazioneOnLines", True, { AziendaFields.Id, DichiarazioneOnLineFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and EventoAziendaEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - EventoAzienda.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property EventoAziendaEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Eventi", True, { AziendaFields.Id, EventoAziendaFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and LicenzaAziendaEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - LicenzaAzienda.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property LicenzaAziendaEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Licenze", True, { AziendaFields.Id, LicenzaAziendaFields.IdAzienda })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and SedeEntity over the 1:n relation they have, using the relation between the fields:
		''' Azienda.Id - Sede.IdAzienda
		''' </summary>
		Public Overridable ReadOnly Property SedeEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Sedi", True, { AziendaFields.Id, SedeFields.IdAzienda })
			End Get				
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and AllegatoEntity over the 1:1 relation they have, using the relation between the fields:
		''' Azienda.Id - Allegato.IdAzienda
		''' </summary>
		Public Overridable  ReadOnly Property AllegatoEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToOne, "Allegatos", true, { AziendaFields.Id, AllegatoFields.IdAzienda })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and CategoriaEntity over the m:1 relation they have, using the relation between the fields:
		''' Azienda.CodCategoria - Categoria.Codice
		''' </summary>
		Public Overridable  ReadOnly Property CategoriaEntityUsingCodCategoria() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Categoria", false, { CategoriaFields.Codice, AziendaFields.CodCategoria })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and FormaGiuridicaEntity over the m:1 relation they have, using the relation between the fields:
		''' Azienda.CodFormaGiuridica - FormaGiuridica.Codice
		''' </summary>
		Public Overridable  ReadOnly Property FormaGiuridicaEntityUsingCodFormaGiuridica() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "FormaGiuridica", false, { FormaGiuridicaFields.Codice, AziendaFields.CodFormaGiuridica })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and InfoStatoEntity over the m:1 relation they have, using the relation between the fields:
		''' Azienda.CodInfoStato - InfoStato.Codice
		''' </summary>
		Public Overridable  ReadOnly Property InfoStatoEntityUsingCodInfoStato() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "InfoStato", false, { InfoStatoFields.Codice, AziendaFields.CodInfoStato })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and StatoSocioEntity over the m:1 relation they have, using the relation between the fields:
		''' Azienda.CodStato - StatoSocio.Codice
		''' </summary>
		Public Overridable  ReadOnly Property StatoSocioEntityUsingCodStato() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "StatoSocio", false, { StatoSocioFields.Codice, AziendaFields.CodStato })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaEntity and TipoSocioEntity over the m:1 relation they have, using the relation between the fields:
		''' Azienda.CodTipoIscrizione - TipoSocio.Codice
		''' </summary>
		Public Overridable  ReadOnly Property TipoSocioEntityUsingCodTipoIscrizione() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "TipoSocio", false, { TipoSocioFields.Codice, AziendaFields.CodTipoIscrizione })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticAziendaRelations
		Friend Shared ReadOnly AziendaAllegatoEntityUsingIdSocioStatic As IEntityRelation = New AziendaRelations().AziendaAllegatoEntityUsingIdSocio
		Friend Shared ReadOnly AttivitaEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().AttivitaEntityUsingIdAzienda
		Friend Shared ReadOnly AziendaProdottoEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().AziendaProdottoEntityUsingIdAzienda
		Friend Shared ReadOnly ContattoEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().ContattoEntityUsingIdAzienda
		Friend Shared ReadOnly DichiarazioneEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().DichiarazioneEntityUsingIdAzienda
		Friend Shared ReadOnly DichiarazioneOnLineEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().DichiarazioneOnLineEntityUsingIdAzienda
		Friend Shared ReadOnly EventoAziendaEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().EventoAziendaEntityUsingIdAzienda
		Friend Shared ReadOnly LicenzaAziendaEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().LicenzaAziendaEntityUsingIdAzienda
		Friend Shared ReadOnly SedeEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().SedeEntityUsingIdAzienda
		Friend Shared ReadOnly AllegatoEntityUsingIdAziendaStatic As IEntityRelation = New AziendaRelations().AllegatoEntityUsingIdAzienda
		Friend Shared ReadOnly CategoriaEntityUsingCodCategoriaStatic As IEntityRelation = New AziendaRelations().CategoriaEntityUsingCodCategoria
		Friend Shared ReadOnly FormaGiuridicaEntityUsingCodFormaGiuridicaStatic As IEntityRelation = New AziendaRelations().FormaGiuridicaEntityUsingCodFormaGiuridica
		Friend Shared ReadOnly InfoStatoEntityUsingCodInfoStatoStatic As IEntityRelation = New AziendaRelations().InfoStatoEntityUsingCodInfoStato
		Friend Shared ReadOnly StatoSocioEntityUsingCodStatoStatic As IEntityRelation = New AziendaRelations().StatoSocioEntityUsingCodStato
		Friend Shared ReadOnly TipoSocioEntityUsingCodTipoIscrizioneStatic As IEntityRelation = New AziendaRelations().TipoSocioEntityUsingCodTipoIscrizione

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
