' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'AziendaProdotto'.<br/><br/></summary>
	<Serializable()> _
	Public Class AziendaProdottoEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _azienda As AziendaEntity
		Private _prodotto As ProdottoEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New AziendaProdottoEntityStaticMetaData()
		Private Shared _relationsFactory As New AziendaProdottoRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Azienda</summary>
			Public Shared ReadOnly [Azienda] As String = "Azienda"
			''' <summary>Member name Prodotto</summary>
			Public Shared ReadOnly [Prodotto] As String = "Prodotto"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class AziendaProdottoEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("AziendaProdottoEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.AziendaProdottoEntity), GetType(AziendaProdottoEntity), GetType(AziendaProdottoEntityFactory), False)
				AddNavigatorMetaData(Of AziendaProdottoEntity, AziendaEntity)("Azienda", "AziendaProdotti", Sub(a, b) a._azienda = b, Function(a) a._azienda, Sub(a, b) a.Azienda = b, DAL.RelationClasses.StaticAziendaProdottoRelations.AziendaEntityUsingIdAziendaStatic, Function() New AziendaProdottoRelations().AziendaEntityUsingIdAzienda, Nothing, New Integer() { CInt(AziendaProdottoFieldIndex.IdAzienda) }, Nothing, True, CInt(DAL.EntityType.AziendaEntity))
				AddNavigatorMetaData(Of AziendaProdottoEntity, ProdottoEntity)("Prodotto", "AziendaProdotti", Sub(a, b) a._prodotto = b, Function(a) a._prodotto, Sub(a, b) a.Prodotto = b, DAL.RelationClasses.StaticAziendaProdottoRelations.ProdottoEntityUsingIdProdottoStatic, Function() New AziendaProdottoRelations().ProdottoEntityUsingIdProdotto, Nothing, New Integer() { CInt(AziendaProdottoFieldIndex.IdProdotto) }, Nothing, True, CInt(DAL.EntityType.ProdottoEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this AziendaProdottoEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for AziendaProdotto which data should be fetched into this AziendaProdotto object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for AziendaProdotto which data should be fetched into this AziendaProdotto object</param>
		''' <param name="validator">The custom validator object for this AziendaProdottoEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Azienda' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoAzienda() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Azienda")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Prodotto' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoProdotto() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Prodotto")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this AziendaProdottoEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As AziendaProdottoRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Azienda' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathAzienda() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Azienda", CommonEntityBase.CreateEntityCollection(Of AziendaEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Prodotto' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathProdotto() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Prodotto", CommonEntityBase.CreateEntityCollection(Of ProdottoEntity)())
			End Get
		End Property

		''' <summary>The Id property of the Entity AziendaProdotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "AziendaProdotto"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(AziendaProdottoFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(AziendaProdottoFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The IdAzienda property of the Entity AziendaProdotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "AziendaProdotto"."IdAzienda".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [IdAzienda]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(AziendaProdottoFieldIndex.IdAzienda), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(AziendaProdottoFieldIndex.IdAzienda), value)
			End Set
		End Property

		''' <summary>The IdProdotto property of the Entity AziendaProdotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "AziendaProdotto"."IdProdotto".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [IdProdotto]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(AziendaProdottoFieldIndex.IdProdotto), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(AziendaProdottoFieldIndex.IdProdotto), value)
			End Set
		End Property

		''' <summary>The Note property of the Entity AziendaProdotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "AziendaProdotto"."Note".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Note]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaProdottoFieldIndex.Note), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaProdottoFieldIndex.Note), value)
			End Set
		End Property

		''' <summary>The TipoUtilizzo property of the Entity AziendaProdotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "AziendaProdotto"."TipoUtilizzo".<br/>Table field type characteristics (type, precision, scale, length): Char, 0, 0, 1.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [TipoUtilizzo]() As System.String
			Get
				Return CType(GetValue(CInt(AziendaProdottoFieldIndex.TipoUtilizzo), True), System.String)
			End Get
			Set
				SetValue(CInt(AziendaProdottoFieldIndex.TipoUtilizzo), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'AziendaEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Azienda]() As AziendaEntity
			Get
				Return _azienda
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Azienda") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'ProdottoEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Prodotto]() As ProdottoEntity
			Get
				Return _prodotto
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Prodotto") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: AziendaProdotto.</summary>
	Public Enum AziendaProdottoFieldIndex
		[Id]
		[IdAzienda]
		[IdProdotto]
		[Note]
		[TipoUtilizzo]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: AziendaProdotto.</summary>
	Public Class AziendaProdottoRelations



		''' <summary>Returns a new IEntityRelation Object, between AziendaProdottoEntity and AziendaEntity over the m:1 relation they have, using the relation between the fields:
		''' AziendaProdotto.IdAzienda - Azienda.Id
		''' </summary>
		Public Overridable  ReadOnly Property AziendaEntityUsingIdAzienda() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Azienda", false, { AziendaFields.Id, AziendaProdottoFields.IdAzienda })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between AziendaProdottoEntity and ProdottoEntity over the m:1 relation they have, using the relation between the fields:
		''' AziendaProdotto.IdProdotto - Prodotto.Id
		''' </summary>
		Public Overridable  ReadOnly Property ProdottoEntityUsingIdProdotto() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Prodotto", false, { ProdottoFields.Id, AziendaProdottoFields.IdProdotto })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticAziendaProdottoRelations
		Friend Shared ReadOnly AziendaEntityUsingIdAziendaStatic As IEntityRelation = New AziendaProdottoRelations().AziendaEntityUsingIdAzienda
		Friend Shared ReadOnly ProdottoEntityUsingIdProdottoStatic As IEntityRelation = New AziendaProdottoRelations().ProdottoEntityUsingIdProdotto

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
