' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Comune'.<br/><br/></summary>
	<Serializable()> _
	Public Class ComuneEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _provincia As ProvinciaEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New ComuneEntityStaticMetaData()
		Private Shared _relationsFactory As New ComuneRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Provincia</summary>
			Public Shared ReadOnly [Provincia] As String = "Provincia"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class ComuneEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("ComuneEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.ComuneEntity), GetType(ComuneEntity), GetType(ComuneEntityFactory), False)
				AddNavigatorMetaData(Of ComuneEntity, ProvinciaEntity)("Provincia", "Comuni", Sub(a, b) a._provincia = b, Function(a) a._provincia, Sub(a, b) a.Provincia = b, DAL.RelationClasses.StaticComuneRelations.ProvinciaEntityUsingCodProvinciaStatic, Function() New ComuneRelations().ProvinciaEntityUsingCodProvincia, Nothing, New Integer() { CInt(ComuneFieldIndex.CodProvincia) }, Nothing, True, CInt(DAL.EntityType.ProvinciaEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this ComuneEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="codice">PK value for Comune which data should be fetched into this Comune object</param>
		Public Sub New(codice As System.String)
			Me.New(codice, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="codice">PK value for Comune which data should be fetched into this Comune object</param>
		''' <param name="validator">The custom validator object for this ComuneEntity</param>
		Public Sub New(codice As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Codice = codice
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Provincia' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoProvincia() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Provincia")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this ComuneEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As ComuneRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Provincia' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathProvincia() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Provincia", CommonEntityBase.CreateEntityCollection(Of ProvinciaEntity)())
			End Get
		End Property

		''' <summary>The Cap property of the Entity Comune<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Comune"."Cap".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 6.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Cap]() As System.String
			Get
				Return CType(GetValue(CInt(ComuneFieldIndex.Cap), True), System.String)
			End Get
			Set
				SetValue(CInt(ComuneFieldIndex.Cap), value)
			End Set
		End Property

		''' <summary>The Codice property of the Entity Comune<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Comune"."Codice".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [Codice]() As System.String
			Get
				Return CType(GetValue(CInt(ComuneFieldIndex.Codice), True), System.String)
			End Get
			Set
				SetValue(CInt(ComuneFieldIndex.Codice), value)
			End Set
		End Property

		''' <summary>The CodProvincia property of the Entity Comune<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Comune"."Cod_Provincia".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 3.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodProvincia]() As System.String
			Get
				Return CType(GetValue(CInt(ComuneFieldIndex.CodProvincia), True), System.String)
			End Get
			Set
				SetValue(CInt(ComuneFieldIndex.CodProvincia), value)
			End Set
		End Property

		''' <summary>The Descrizione property of the Entity Comune<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Comune"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(ComuneFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(ComuneFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>The Estera property of the Entity Comune<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Comune"."Estera".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Estera]() As Nullable(Of System.Boolean)
			Get
				Return CType(GetValue(CInt(ComuneFieldIndex.Estera), False), Nullable(Of System.Boolean))
			End Get
			Set
				SetValue(CInt(ComuneFieldIndex.Estera), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'ProvinciaEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Provincia]() As ProvinciaEntity
			Get
				Return _provincia
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Provincia") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Comune.</summary>
	Public Enum ComuneFieldIndex
		[Cap]
		[Codice]
		[CodProvincia]
		[Descrizione]
		[Estera]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Comune.</summary>
	Public Class ComuneRelations



		''' <summary>Returns a new IEntityRelation Object, between ComuneEntity and ProvinciaEntity over the m:1 relation they have, using the relation between the fields:
		''' Comune.CodProvincia - Provincia.Codice
		''' </summary>
		Public Overridable  ReadOnly Property ProvinciaEntityUsingCodProvincia() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Provincia", false, { ProvinciaFields.Codice, ComuneFields.CodProvincia })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticComuneRelations
		Friend Shared ReadOnly ProvinciaEntityUsingCodProvinciaStatic As IEntityRelation = New ComuneRelations().ProvinciaEntityUsingCodProvincia

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
