' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Evento'.<br/><br/></summary>
	<Serializable()> _
	Public Class EventoEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _eventiFigli As EntityCollection(Of EventoEntity)
		Private _eventoPadre As EventoEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New EventoEntityStaticMetaData()
		Private Shared _relationsFactory As New EventoRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name EventoPadre</summary>
			Public Shared ReadOnly [EventoPadre] As String = "EventoPadre"
			''' <summary>Member name EventiFigli</summary>
			Public Shared ReadOnly [EventiFigli] As String  = "EventiFigli"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class EventoEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("EventoEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.EventoEntity), GetType(EventoEntity), GetType(EventoEntityFactory), False)
				AddNavigatorMetaData(Of EventoEntity, EntityCollection(Of EventoEntity))("EventiFigli", Function(a) a._eventiFigli, Sub(a, b) a._eventiFigli = b, Function(a) a.EventiFigli, Function() New EventoRelations().EventoEntityUsingCodEventoPrecedente, GetType(EventoEntity), CInt(DAL.EntityType.EventoEntity))
				AddNavigatorMetaData(Of EventoEntity, EventoEntity)("EventoPadre", "EventiFigli", Sub(a, b) a._eventoPadre = b, Function(a) a._eventoPadre, Sub(a, b) a.EventoPadre = b, DAL.RelationClasses.StaticEventoRelations.EventoEntityUsingCodiceCodEventoPrecedenteStatic, Function() New EventoRelations().EventoEntityUsingCodiceCodEventoPrecedente, Nothing, New Integer() { CInt(EventoFieldIndex.CodEventoPrecedente) }, Nothing, True, CInt(DAL.EntityType.EventoEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this EventoEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="codice">PK value for Evento which data should be fetched into this Evento object</param>
		Public Sub New(codice As System.String)
			Me.New(codice, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="codice">PK value for Evento which data should be fetched into this Evento object</param>
		''' <param name="validator">The custom validator object for this EventoEntity</param>
		Public Sub New(codice As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Codice = codice
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Evento' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoEventiFigli() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("EventiFigli")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Evento' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoEventoPadre() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("EventoPadre")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this EventoEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As EventoRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Evento'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathEventiFigli() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("EventiFigli", CommonEntityBase.CreateEntityCollection(Of EventoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Evento' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathEventoPadre() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("EventoPadre", CommonEntityBase.CreateEntityCollection(Of EventoEntity)())
			End Get
		End Property

		''' <summary>The CodEventoPrecedente property of the Entity Evento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Evento"."CodEventoPrecedente".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodEventoPrecedente]() As System.String
			Get
				Return CType(GetValue(CInt(EventoFieldIndex.CodEventoPrecedente), True), System.String)
			End Get
			Set
				SetValue(CInt(EventoFieldIndex.CodEventoPrecedente), value)
			End Set
		End Property

		''' <summary>The Codice property of the Entity Evento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Evento"."Codice".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [Codice]() As System.String
			Get
				Return CType(GetValue(CInt(EventoFieldIndex.Codice), True), System.String)
			End Get
			Set
				SetValue(CInt(EventoFieldIndex.Codice), value)
			End Set
		End Property

		''' <summary>The CodStato property of the Entity Evento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Evento"."CodStato".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodStato]() As System.String
			Get
				Return CType(GetValue(CInt(EventoFieldIndex.CodStato), True), System.String)
			End Get
			Set
				SetValue(CInt(EventoFieldIndex.CodStato), value)
			End Set
		End Property

		''' <summary>The Descrizione property of the Entity Evento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Evento"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(EventoFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(EventoFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>The Nome property of the Entity Evento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Evento"."Nome".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Nome]() As System.String
			Get
				Return CType(GetValue(CInt(EventoFieldIndex.Nome), True), System.String)
			End Get
			Set
				SetValue(CInt(EventoFieldIndex.Nome), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'EventoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(EventoEntity))> _
		Public Overridable ReadOnly Property [EventiFigli]() As EntityCollection(Of EventoEntity)
			Get
				Return GetOrCreateEntityCollection(Of EventoEntity, EventoEntityFactory)("EventoPadre", true, false, _eventiFigli)
			End Get
		End Property


		''' <summary>Gets / sets related entity of type 'EventoEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [EventoPadre]() As EventoEntity
			Get
				Return _eventoPadre
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "EventoPadre") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Evento.</summary>
	Public Enum EventoFieldIndex
		[CodEventoPrecedente]
		[Codice]
		[CodStato]
		[Descrizione]
		[Nome]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Evento.</summary>
	Public Class EventoRelations

		''' <summary>Returns a new IEntityRelation Object, between EventoEntity and EventoEntity over the 1:n relation they have, using the relation between the fields:
		''' Evento.Codice - Evento.CodEventoPrecedente
		''' </summary>
		Public Overridable ReadOnly Property EventoEntityUsingCodEventoPrecedente() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "EventiFigli", True, { EventoFields.Codice, EventoFields.CodEventoPrecedente })
			End Get				
		End Property


		''' <summary>Returns a new IEntityRelation Object, between EventoEntity and EventoEntity over the m:1 relation they have, using the relation between the fields:
		''' Evento.CodEventoPrecedente - Evento.Codice
		''' </summary>
		Public Overridable  ReadOnly Property EventoEntityUsingCodiceCodEventoPrecedente() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "EventoPadre", false, { EventoFields.Codice, EventoFields.CodEventoPrecedente })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticEventoRelations
		Friend Shared ReadOnly EventoEntityUsingCodEventoPrecedenteStatic As IEntityRelation = New EventoRelations().EventoEntityUsingCodEventoPrecedente
		Friend Shared ReadOnly EventoEntityUsingCodiceCodEventoPrecedenteStatic As IEntityRelation = New EventoRelations().EventoEntityUsingCodiceCodEventoPrecedente

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
