' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Incasso'.<br/><br/></summary>
	<Serializable()> _
	Public Class IncassoEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _dichiarazione As DichiarazioneEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New IncassoEntityStaticMetaData()
		Private Shared _relationsFactory As New IncassoRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Dichiarazione</summary>
			Public Shared ReadOnly [Dichiarazione] As String = "Dichiarazione"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class IncassoEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("IncassoEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.IncassoEntity), GetType(IncassoEntity), GetType(IncassoEntityFactory), False)
				AddNavigatorMetaData(Of IncassoEntity, DichiarazioneEntity)("Dichiarazione", "Incassi", Sub(a, b) a._dichiarazione = b, Function(a) a._dichiarazione, Sub(a, b) a.Dichiarazione = b, DAL.RelationClasses.StaticIncassoRelations.DichiarazioneEntityUsingIdDichiarazioneStatic, Function() New IncassoRelations().DichiarazioneEntityUsingIdDichiarazione, Nothing, New Integer() { CInt(IncassoFieldIndex.IdDichiarazione) }, Nothing, True, CInt(DAL.EntityType.DichiarazioneEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this IncassoEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for Incasso which data should be fetched into this Incasso object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for Incasso which data should be fetched into this Incasso object</param>
		''' <param name="validator">The custom validator object for this IncassoEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Dichiarazione' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoDichiarazione() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Dichiarazione")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this IncassoEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As IncassoRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Dichiarazione' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathDichiarazione() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Dichiarazione", CommonEntityBase.CreateEntityCollection(Of DichiarazioneEntity)())
			End Get
		End Property

		''' <summary>The CodModalitaPagamento property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."CodModalitaPagamento".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [CodModalitaPagamento]() As System.String
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.CodModalitaPagamento), True), System.String)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.CodModalitaPagamento), value)
			End Set
		End Property

		''' <summary>The CodTipo property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."CodTipo".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [CodTipo]() As System.String
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.CodTipo), True), System.String)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.CodTipo), value)
			End Set
		End Property

		''' <summary>The DataEsportazione property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."DataEsportazione".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataEsportazione]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.DataEsportazione), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.DataEsportazione), value)
			End Set
		End Property

		''' <summary>The DataInserimento property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."DataInserimento".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [DataInserimento]() As System.DateTime
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.DataInserimento), True), System.DateTime)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.DataInserimento), value)
			End Set
		End Property

		''' <summary>The DataPagamento property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."DataPagamento".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataPagamento]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.DataPagamento), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.DataPagamento), value)
			End Set
		End Property

		''' <summary>The DataScadenza property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."DataScadenza".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataScadenza]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.DataScadenza), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.DataScadenza), value)
			End Set
		End Property

		''' <summary>The DataValuta property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."DataValuta".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataValuta]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.DataValuta), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.DataValuta), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The IdDichiarazione property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."IdDichiarazione".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [IdDichiarazione]() As System.Int32
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.IdDichiarazione), True), System.Int32)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.IdDichiarazione), value)
			End Set
		End Property

		''' <summary>The Importo property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."Importo".<br/>Table field type characteristics (type, precision, scale, length): Money, 19, 4, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Importo]() As System.Decimal
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.Importo), True), System.Decimal)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.Importo), value)
			End Set
		End Property

		''' <summary>The IsAcconto property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."IsAcconto".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [IsAcconto]() As System.Boolean
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.IsAcconto), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.IsAcconto), value)
			End Set
		End Property

		''' <summary>The Note property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."Note".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Note]() As System.String
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.Note), True), System.String)
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.Note), value)
			End Set
		End Property

		''' <summary>The NumeroRata property of the Entity Incasso<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Incasso"."NumeroRata".<br/>Table field type characteristics (type, precision, scale, length): SmallInt, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [NumeroRata]() As Nullable(Of System.Int16)
			Get
				Return CType(GetValue(CInt(IncassoFieldIndex.NumeroRata), False), Nullable(Of System.Int16))
			End Get
			Set
				SetValue(CInt(IncassoFieldIndex.NumeroRata), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'DichiarazioneEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Dichiarazione]() As DichiarazioneEntity
			Get
				Return _dichiarazione
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Dichiarazione") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Incasso.</summary>
	Public Enum IncassoFieldIndex
		[CodModalitaPagamento]
		[CodTipo]
		[DataEsportazione]
		[DataInserimento]
		[DataPagamento]
		[DataScadenza]
		[DataValuta]
		[Id]
		[IdDichiarazione]
		[Importo]
		[IsAcconto]
		[Note]
		[NumeroRata]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Incasso.</summary>
	Public Class IncassoRelations



		''' <summary>Returns a new IEntityRelation Object, between IncassoEntity and DichiarazioneEntity over the m:1 relation they have, using the relation between the fields:
		''' Incasso.IdDichiarazione - Dichiarazione.Id
		''' </summary>
		Public Overridable  ReadOnly Property DichiarazioneEntityUsingIdDichiarazione() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Dichiarazione", false, { DichiarazioneFields.Id, IncassoFields.IdDichiarazione })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticIncassoRelations
		Friend Shared ReadOnly DichiarazioneEntityUsingIdDichiarazioneStatic As IEntityRelation = New IncassoRelations().DichiarazioneEntityUsingIdDichiarazione

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
