' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'MaterialeQuadro'.<br/><br/></summary>
	<Serializable()> _
	Public Class MaterialeQuadroEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _materiale As MaterialeEntity
		Private _quadro As QuadroEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New MaterialeQuadroEntityStaticMetaData()
		Private Shared _relationsFactory As New MaterialeQuadroRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Materiale</summary>
			Public Shared ReadOnly [Materiale] As String = "Materiale"
			''' <summary>Member name Quadro</summary>
			Public Shared ReadOnly [Quadro] As String = "Quadro"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class MaterialeQuadroEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("MaterialeQuadroEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.MaterialeQuadroEntity), GetType(MaterialeQuadroEntity), GetType(MaterialeQuadroEntityFactory), False)
				AddNavigatorMetaData(Of MaterialeQuadroEntity, MaterialeEntity)("Materiale", "MaterialeQuadri", Sub(a, b) a._materiale = b, Function(a) a._materiale, Sub(a, b) a.Materiale = b, DAL.RelationClasses.StaticMaterialeQuadroRelations.MaterialeEntityUsingIdMaterialeStatic, Function() New MaterialeQuadroRelations().MaterialeEntityUsingIdMateriale, Nothing, New Integer() { CInt(MaterialeQuadroFieldIndex.IdMateriale) }, Nothing, True, CInt(DAL.EntityType.MaterialeEntity))
				AddNavigatorMetaData(Of MaterialeQuadroEntity, QuadroEntity)("Quadro", "MaterialiQuadro", Sub(a, b) a._quadro = b, Function(a) a._quadro, Sub(a, b) a.Quadro = b, DAL.RelationClasses.StaticMaterialeQuadroRelations.QuadroEntityUsingIdQuadroStatic, Function() New MaterialeQuadroRelations().QuadroEntityUsingIdQuadro, Nothing, New Integer() { CInt(MaterialeQuadroFieldIndex.IdQuadro) }, Nothing, True, CInt(DAL.EntityType.QuadroEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this MaterialeQuadroEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="idMateriale">PK value for MaterialeQuadro which data should be fetched into this MaterialeQuadro object</param>
		''' <param name="idQuadro">PK value for MaterialeQuadro which data should be fetched into this MaterialeQuadro object</param>
		Public Sub New(idMateriale As System.Int32, idQuadro As System.Int32)
			Me.New(idMateriale, idQuadro, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="idMateriale">PK value for MaterialeQuadro which data should be fetched into this MaterialeQuadro object</param>
		''' <param name="idQuadro">PK value for MaterialeQuadro which data should be fetched into this MaterialeQuadro object</param>
		''' <param name="validator">The custom validator object for this MaterialeQuadroEntity</param>
		Public Sub New(idMateriale As System.Int32, idQuadro As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.IdMateriale = idMateriale
			Me.IdQuadro = idQuadro
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Materiale' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoMateriale() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Materiale")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Quadro' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoQuadro() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Quadro")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this MaterialeQuadroEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As MaterialeQuadroRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Materiale' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathMateriale() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Materiale", CommonEntityBase.CreateEntityCollection(Of MaterialeEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Quadro' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathQuadro() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Quadro", CommonEntityBase.CreateEntityCollection(Of QuadroEntity)())
			End Get
		End Property

		''' <summary>The IdMateriale property of the Entity MaterialeQuadro<br/><br/></summary>
		''' <remarks> Mapped on  table field: "MaterialeQuadro"."IdMateriale".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [IdMateriale]() As System.Int32
			Get
				Return CType(GetValue(CInt(MaterialeQuadroFieldIndex.IdMateriale), True), System.Int32)
			End Get
			Set
				SetValue(CInt(MaterialeQuadroFieldIndex.IdMateriale), value)
			End Set
		End Property

		''' <summary>The IdQuadro property of the Entity MaterialeQuadro<br/><br/></summary>
		''' <remarks> Mapped on  table field: "MaterialeQuadro"."IdQuadro".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [IdQuadro]() As System.Int32
			Get
				Return CType(GetValue(CInt(MaterialeQuadroFieldIndex.IdQuadro), True), System.Int32)
			End Get
			Set
				SetValue(CInt(MaterialeQuadroFieldIndex.IdQuadro), value)
			End Set
		End Property

		''' <summary>The Posizione property of the Entity MaterialeQuadro<br/><br/></summary>
		''' <remarks> Mapped on  table field: "MaterialeQuadro"."Posizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Posizione]() As System.String
			Get
				Return CType(GetValue(CInt(MaterialeQuadroFieldIndex.Posizione), True), System.String)
			End Get
			Set
				SetValue(CInt(MaterialeQuadroFieldIndex.Posizione), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'MaterialeEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Materiale]() As MaterialeEntity
			Get
				Return _materiale
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Materiale") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'QuadroEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Quadro]() As QuadroEntity
			Get
				Return _quadro
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Quadro") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: MaterialeQuadro.</summary>
	Public Enum MaterialeQuadroFieldIndex
		[IdMateriale]
		[IdQuadro]
		[Posizione]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: MaterialeQuadro.</summary>
	Public Class MaterialeQuadroRelations



		''' <summary>Returns a new IEntityRelation Object, between MaterialeQuadroEntity and MaterialeEntity over the m:1 relation they have, using the relation between the fields:
		''' MaterialeQuadro.IdMateriale - Materiale.Id
		''' </summary>
		Public Overridable  ReadOnly Property MaterialeEntityUsingIdMateriale() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Materiale", false, { MaterialeFields.Id, MaterialeQuadroFields.IdMateriale })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between MaterialeQuadroEntity and QuadroEntity over the m:1 relation they have, using the relation between the fields:
		''' MaterialeQuadro.IdQuadro - Quadro.Id
		''' </summary>
		Public Overridable  ReadOnly Property QuadroEntityUsingIdQuadro() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Quadro", false, { QuadroFields.Id, MaterialeQuadroFields.IdQuadro })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticMaterialeQuadroRelations
		Friend Shared ReadOnly MaterialeEntityUsingIdMaterialeStatic As IEntityRelation = New MaterialeQuadroRelations().MaterialeEntityUsingIdMateriale
		Friend Shared ReadOnly QuadroEntityUsingIdQuadroStatic As IEntityRelation = New MaterialeQuadroRelations().QuadroEntityUsingIdQuadro

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
