' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'ModalitaPagamento'.<br/><br/></summary>
	<Serializable()> _
	Public Class ModalitaPagamentoEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New ModalitaPagamentoEntityStaticMetaData()
		Private Shared _relationsFactory As New ModalitaPagamentoRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class ModalitaPagamentoEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("ModalitaPagamentoEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.ModalitaPagamentoEntity), GetType(ModalitaPagamentoEntity), GetType(ModalitaPagamentoEntityFactory), False)
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this ModalitaPagamentoEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="codice">PK value for ModalitaPagamento which data should be fetched into this ModalitaPagamento object</param>
		Public Sub New(codice As System.String)
			Me.New(codice, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="codice">PK value for ModalitaPagamento which data should be fetched into this ModalitaPagamento object</param>
		''' <param name="validator">The custom validator object for this ModalitaPagamentoEntity</param>
		Public Sub New(codice As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Codice = codice
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this ModalitaPagamentoEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As ModalitaPagamentoRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>The Codice property of the Entity ModalitaPagamento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ModalitaPagamento"."Codice".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [Codice]() As System.String
			Get
				Return CType(GetValue(CInt(ModalitaPagamentoFieldIndex.Codice), True), System.String)
			End Get
			Set
				SetValue(CInt(ModalitaPagamentoFieldIndex.Codice), value)
			End Set
		End Property

		''' <summary>The Descrizione property of the Entity ModalitaPagamento<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ModalitaPagamento"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(ModalitaPagamentoFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(ModalitaPagamentoFieldIndex.Descrizione), value)
			End Set
		End Property





		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: ModalitaPagamento.</summary>
	Public Enum ModalitaPagamentoFieldIndex
		[Codice]
		[Descrizione]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: ModalitaPagamento.</summary>
	Public Class ModalitaPagamentoRelations



	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticModalitaPagamentoRelations

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
