' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'ProdottoDichiarato'.<br/><br/></summary>
	<Serializable()> _
	Public Class ProdottoDichiaratoEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _dichiarazione As DichiarazioneEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New ProdottoDichiaratoEntityStaticMetaData()
		Private Shared _relationsFactory As New ProdottoDichiaratoRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Dichiarazione</summary>
			Public Shared ReadOnly [Dichiarazione] As String = "Dichiarazione"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class ProdottoDichiaratoEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("ProdottoDichiaratoEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.ProdottoDichiaratoEntity), GetType(ProdottoDichiaratoEntity), GetType(ProdottoDichiaratoEntityFactory), False)
				AddNavigatorMetaData(Of ProdottoDichiaratoEntity, DichiarazioneEntity)("Dichiarazione", "ElencoProdottiDichiarati", Sub(a, b) a._dichiarazione = b, Function(a) a._dichiarazione, Sub(a, b) a.Dichiarazione = b, DAL.RelationClasses.StaticProdottoDichiaratoRelations.DichiarazioneEntityUsingIdDichiarazioneStatic, Function() New ProdottoDichiaratoRelations().DichiarazioneEntityUsingIdDichiarazione, Nothing, New Integer() { CInt(ProdottoDichiaratoFieldIndex.IdDichiarazione) }, Nothing, True, CInt(DAL.EntityType.DichiarazioneEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this ProdottoDichiaratoEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for ProdottoDichiarato which data should be fetched into this ProdottoDichiarato object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for ProdottoDichiarato which data should be fetched into this ProdottoDichiarato object</param>
		''' <param name="validator">The custom validator object for this ProdottoDichiaratoEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Dichiarazione' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoDichiarazione() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Dichiarazione")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this ProdottoDichiaratoEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As ProdottoDichiaratoRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Dichiarazione' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathDichiarazione() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Dichiarazione", CommonEntityBase.CreateEntityCollection(Of DichiarazioneEntity)())
			End Get
		End Property

		''' <summary>The Descrizione property of the Entity ProdottoDichiarato<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ProdottoDichiarato"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(ProdottoDichiaratoFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(ProdottoDichiaratoFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity ProdottoDichiarato<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ProdottoDichiarato"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(ProdottoDichiaratoFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(ProdottoDichiaratoFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The IdDichiarazione property of the Entity ProdottoDichiarato<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ProdottoDichiarato"."IdDichiarazione".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [IdDichiarazione]() As System.Int32
			Get
				Return CType(GetValue(CInt(ProdottoDichiaratoFieldIndex.IdDichiarazione), True), System.Int32)
			End Get
			Set
				SetValue(CInt(ProdottoDichiaratoFieldIndex.IdDichiarazione), value)
			End Set
		End Property

		''' <summary>The QtaRiciclato property of the Entity ProdottoDichiarato<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ProdottoDichiarato"."QtaRiciclato".<br/>Table field type characteristics (type, precision, scale, length): Decimal, 18, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [QtaRiciclato]() As Nullable(Of System.Decimal)
			Get
				Return CType(GetValue(CInt(ProdottoDichiaratoFieldIndex.QtaRiciclato), False), Nullable(Of System.Decimal))
			End Get
			Set
				SetValue(CInt(ProdottoDichiaratoFieldIndex.QtaRiciclato), value)
			End Set
		End Property

		''' <summary>The QtaVergine property of the Entity ProdottoDichiarato<br/><br/></summary>
		''' <remarks> Mapped on  table field: "ProdottoDichiarato"."QtaVergine".<br/>Table field type characteristics (type, precision, scale, length): Decimal, 18, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [QtaVergine]() As Nullable(Of System.Decimal)
			Get
				Return CType(GetValue(CInt(ProdottoDichiaratoFieldIndex.QtaVergine), False), Nullable(Of System.Decimal))
			End Get
			Set
				SetValue(CInt(ProdottoDichiaratoFieldIndex.QtaVergine), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'DichiarazioneEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Dichiarazione]() As DichiarazioneEntity
			Get
				Return _dichiarazione
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Dichiarazione") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: ProdottoDichiarato.</summary>
	Public Enum ProdottoDichiaratoFieldIndex
		[Descrizione]
		[Id]
		[IdDichiarazione]
		[QtaRiciclato]
		[QtaVergine]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: ProdottoDichiarato.</summary>
	Public Class ProdottoDichiaratoRelations



		''' <summary>Returns a new IEntityRelation Object, between ProdottoDichiaratoEntity and DichiarazioneEntity over the m:1 relation they have, using the relation between the fields:
		''' ProdottoDichiarato.IdDichiarazione - Dichiarazione.Id
		''' </summary>
		Public Overridable  ReadOnly Property DichiarazioneEntityUsingIdDichiarazione() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Dichiarazione", false, { DichiarazioneFields.Id, ProdottoDichiaratoFields.IdDichiarazione })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticProdottoDichiaratoRelations
		Friend Shared ReadOnly DichiarazioneEntityUsingIdDichiarazioneStatic As IEntityRelation = New ProdottoDichiaratoRelations().DichiarazioneEntityUsingIdDichiarazione

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
