' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Prodotto'.<br/><br/></summary>
	<Serializable()> _
	Public Class ProdottoEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _aziendaProdotti As EntityCollection(Of AziendaProdottoEntity)
		Private _sottoProdotti As EntityCollection(Of ProdottoEntity)
		Private _prodottoPadre As ProdottoEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New ProdottoEntityStaticMetaData()
		Private Shared _relationsFactory As New ProdottoRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name ProdottoPadre</summary>
			Public Shared ReadOnly [ProdottoPadre] As String = "ProdottoPadre"
			''' <summary>Member name AziendaProdotti</summary>
			Public Shared ReadOnly [AziendaProdotti] As String  = "AziendaProdotti"
			''' <summary>Member name SottoProdotti</summary>
			Public Shared ReadOnly [SottoProdotti] As String  = "SottoProdotti"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class ProdottoEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("ProdottoEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.ProdottoEntity), GetType(ProdottoEntity), GetType(ProdottoEntityFactory), False)
				AddNavigatorMetaData(Of ProdottoEntity, EntityCollection(Of AziendaProdottoEntity))("AziendaProdotti", Function(a) a._aziendaProdotti, Sub(a, b) a._aziendaProdotti = b, Function(a) a.AziendaProdotti, Function() New ProdottoRelations().AziendaProdottoEntityUsingIdProdotto, GetType(AziendaProdottoEntity), CInt(DAL.EntityType.AziendaProdottoEntity))
				AddNavigatorMetaData(Of ProdottoEntity, EntityCollection(Of ProdottoEntity))("SottoProdotti", Function(a) a._sottoProdotti, Sub(a, b) a._sottoProdotti = b, Function(a) a.SottoProdotti, Function() New ProdottoRelations().ProdottoEntityUsingIdRiferimento, GetType(ProdottoEntity), CInt(DAL.EntityType.ProdottoEntity))
				AddNavigatorMetaData(Of ProdottoEntity, ProdottoEntity)("ProdottoPadre", "SottoProdotti", Sub(a, b) a._prodottoPadre = b, Function(a) a._prodottoPadre, Sub(a, b) a.ProdottoPadre = b, DAL.RelationClasses.StaticProdottoRelations.ProdottoEntityUsingIdIdRiferimentoStatic, Function() New ProdottoRelations().ProdottoEntityUsingIdIdRiferimento, Nothing, New Integer() { CInt(ProdottoFieldIndex.IdRiferimento) }, Nothing, True, CInt(DAL.EntityType.ProdottoEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this ProdottoEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for Prodotto which data should be fetched into this Prodotto object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for Prodotto which data should be fetched into this Prodotto object</param>
		''' <param name="validator">The custom validator object for this ProdottoEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'AziendaProdotto' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoAziendaProdotti() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("AziendaProdotti")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Prodotto' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoSottoProdotti() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("SottoProdotti")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Prodotto' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoProdottoPadre() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("ProdottoPadre")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this ProdottoEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As ProdottoRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'AziendaProdotto'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathAziendaProdotti() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("AziendaProdotti", CommonEntityBase.CreateEntityCollection(Of AziendaProdottoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Prodotto'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathSottoProdotti() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("SottoProdotti", CommonEntityBase.CreateEntityCollection(Of ProdottoEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Prodotto' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathProdottoPadre() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("ProdottoPadre", CommonEntityBase.CreateEntityCollection(Of ProdottoEntity)())
			End Get
		End Property

		''' <summary>The Descrizione property of the Entity Prodotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Prodotto"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(ProdottoFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(ProdottoFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity Prodotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Prodotto"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(ProdottoFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(ProdottoFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The IdRiferimento property of the Entity Prodotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Prodotto"."IdRiferimento".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [IdRiferimento]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(ProdottoFieldIndex.IdRiferimento), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(ProdottoFieldIndex.IdRiferimento), value)
			End Set
		End Property

		''' <summary>The Livello property of the Entity Prodotto<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Prodotto"."Livello".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Livello]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(ProdottoFieldIndex.Livello), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(ProdottoFieldIndex.Livello), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'AziendaProdottoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(AziendaProdottoEntity))> _
		Public Overridable ReadOnly Property [AziendaProdotti]() As EntityCollection(Of AziendaProdottoEntity)
			Get
				Return GetOrCreateEntityCollection(Of AziendaProdottoEntity, AziendaProdottoEntityFactory)("Prodotto", true, false, _aziendaProdotti)
			End Get
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'ProdottoEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(ProdottoEntity))> _
		Public Overridable ReadOnly Property [SottoProdotti]() As EntityCollection(Of ProdottoEntity)
			Get
				Return GetOrCreateEntityCollection(Of ProdottoEntity, ProdottoEntityFactory)("ProdottoPadre", true, false, _sottoProdotti)
			End Get
		End Property


		''' <summary>Gets / sets related entity of type 'ProdottoEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [ProdottoPadre]() As ProdottoEntity
			Get
				Return _prodottoPadre
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "ProdottoPadre") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Prodotto.</summary>
	Public Enum ProdottoFieldIndex
		[Descrizione]
		[Id]
		[IdRiferimento]
		[Livello]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Prodotto.</summary>
	Public Class ProdottoRelations

		''' <summary>Returns a new IEntityRelation Object, between ProdottoEntity and AziendaProdottoEntity over the 1:n relation they have, using the relation between the fields:
		''' Prodotto.Id - AziendaProdotto.IdProdotto
		''' </summary>
		Public Overridable ReadOnly Property AziendaProdottoEntityUsingIdProdotto() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "AziendaProdotti", True, { ProdottoFields.Id, AziendaProdottoFields.IdProdotto })
			End Get				
		End Property
		''' <summary>Returns a new IEntityRelation Object, between ProdottoEntity and ProdottoEntity over the 1:n relation they have, using the relation between the fields:
		''' Prodotto.Id - Prodotto.IdRiferimento
		''' </summary>
		Public Overridable ReadOnly Property ProdottoEntityUsingIdRiferimento() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "SottoProdotti", True, { ProdottoFields.Id, ProdottoFields.IdRiferimento })
			End Get				
		End Property


		''' <summary>Returns a new IEntityRelation Object, between ProdottoEntity and ProdottoEntity over the m:1 relation they have, using the relation between the fields:
		''' Prodotto.IdRiferimento - Prodotto.Id
		''' </summary>
		Public Overridable  ReadOnly Property ProdottoEntityUsingIdIdRiferimento() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProdottoPadre", false, { ProdottoFields.Id, ProdottoFields.IdRiferimento })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticProdottoRelations
		Friend Shared ReadOnly AziendaProdottoEntityUsingIdProdottoStatic As IEntityRelation = New ProdottoRelations().AziendaProdottoEntityUsingIdProdotto
		Friend Shared ReadOnly ProdottoEntityUsingIdRiferimentoStatic As IEntityRelation = New ProdottoRelations().ProdottoEntityUsingIdRiferimento
		Friend Shared ReadOnly ProdottoEntityUsingIdIdRiferimentoStatic As IEntityRelation = New ProdottoRelations().ProdottoEntityUsingIdIdRiferimento

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
