' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Provincia'.<br/><br/></summary>
	<Serializable()> _
	Public Class ProvinciaEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _comuni As EntityCollection(Of ComuneEntity)
		Private _regione As RegioneEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New ProvinciaEntityStaticMetaData()
		Private Shared _relationsFactory As New ProvinciaRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Regione</summary>
			Public Shared ReadOnly [Regione] As String = "Regione"
			''' <summary>Member name Comuni</summary>
			Public Shared ReadOnly [Comuni] As String  = "Comuni"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class ProvinciaEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("ProvinciaEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.ProvinciaEntity), GetType(ProvinciaEntity), GetType(ProvinciaEntityFactory), False)
				AddNavigatorMetaData(Of ProvinciaEntity, EntityCollection(Of ComuneEntity))("Comuni", Function(a) a._comuni, Sub(a, b) a._comuni = b, Function(a) a.Comuni, Function() New ProvinciaRelations().ComuneEntityUsingCodProvincia, GetType(ComuneEntity), CInt(DAL.EntityType.ComuneEntity))
				AddNavigatorMetaData(Of ProvinciaEntity, RegioneEntity)("Regione", "Provincie", Sub(a, b) a._regione = b, Function(a) a._regione, Sub(a, b) a.Regione = b, DAL.RelationClasses.StaticProvinciaRelations.RegioneEntityUsingCodRegioneStatic, Function() New ProvinciaRelations().RegioneEntityUsingCodRegione, Nothing, New Integer() { CInt(ProvinciaFieldIndex.CodRegione) }, Nothing, True, CInt(DAL.EntityType.RegioneEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this ProvinciaEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="codice">PK value for Provincia which data should be fetched into this Provincia object</param>
		Public Sub New(codice As System.String)
			Me.New(codice, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="codice">PK value for Provincia which data should be fetched into this Provincia object</param>
		''' <param name="validator">The custom validator object for this ProvinciaEntity</param>
		Public Sub New(codice As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Codice = codice
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Comune' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoComuni() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Comuni")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Regione' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoRegione() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Regione")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this ProvinciaEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As ProvinciaRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Comune'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathComuni() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Comuni", CommonEntityBase.CreateEntityCollection(Of ComuneEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Regione' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathRegione() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Regione", CommonEntityBase.CreateEntityCollection(Of RegioneEntity)())
			End Get
		End Property

		''' <summary>The Codice property of the Entity Provincia<br/><br/></summary>
		''' <remarks> Mapped on  table field: "provincia"."Codice".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 3.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [Codice]() As System.String
			Get
				Return CType(GetValue(CInt(ProvinciaFieldIndex.Codice), True), System.String)
			End Get
			Set
				SetValue(CInt(ProvinciaFieldIndex.Codice), value)
			End Set
		End Property

		''' <summary>The CodRegione property of the Entity Provincia<br/><br/></summary>
		''' <remarks> Mapped on  table field: "provincia"."Cod_Regione".<br/>Table field type characteristics (type, precision, scale, length): Char, 0, 0, 3.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodRegione]() As System.String
			Get
				Return CType(GetValue(CInt(ProvinciaFieldIndex.CodRegione), True), System.String)
			End Get
			Set
				SetValue(CInt(ProvinciaFieldIndex.CodRegione), value)
			End Set
		End Property

		''' <summary>The Descrizione property of the Entity Provincia<br/><br/></summary>
		''' <remarks> Mapped on  table field: "provincia"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(ProvinciaFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(ProvinciaFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'ComuneEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(ComuneEntity))> _
		Public Overridable ReadOnly Property [Comuni]() As EntityCollection(Of ComuneEntity)
			Get
				Return GetOrCreateEntityCollection(Of ComuneEntity, ComuneEntityFactory)("Provincia", true, false, _comuni)
			End Get
		End Property


		''' <summary>Gets / sets related entity of type 'RegioneEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Regione]() As RegioneEntity
			Get
				Return _regione
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Regione") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Provincia.</summary>
	Public Enum ProvinciaFieldIndex
		[Codice]
		[CodRegione]
		[Descrizione]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Provincia.</summary>
	Public Class ProvinciaRelations

		''' <summary>Returns a new IEntityRelation Object, between ProvinciaEntity and ComuneEntity over the 1:n relation they have, using the relation between the fields:
		''' Provincia.Codice - Comune.CodProvincia
		''' </summary>
		Public Overridable ReadOnly Property ComuneEntityUsingCodProvincia() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Comuni", True, { ProvinciaFields.Codice, ComuneFields.CodProvincia })
			End Get				
		End Property


		''' <summary>Returns a new IEntityRelation Object, between ProvinciaEntity and RegioneEntity over the m:1 relation they have, using the relation between the fields:
		''' Provincia.CodRegione - Regione.Codice
		''' </summary>
		Public Overridable  ReadOnly Property RegioneEntityUsingCodRegione() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Regione", false, { RegioneFields.Codice, ProvinciaFields.CodRegione })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticProvinciaRelations
		Friend Shared ReadOnly ComuneEntityUsingCodProvinciaStatic As IEntityRelation = New ProvinciaRelations().ComuneEntityUsingCodProvincia
		Friend Shared ReadOnly RegioneEntityUsingCodRegioneStatic As IEntityRelation = New ProvinciaRelations().RegioneEntityUsingCodRegione

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
