' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'RigaDichiarazione'.<br/><br/></summary>
	<Serializable()> _
	Public Class RigaDichiarazioneEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _dichiarazione As DichiarazioneEntity
		Private _materiale As MaterialeEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New RigaDichiarazioneEntityStaticMetaData()
		Private Shared _relationsFactory As New RigaDichiarazioneRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Dichiarazione</summary>
			Public Shared ReadOnly [Dichiarazione] As String = "Dichiarazione"
			''' <summary>Member name Materiale</summary>
			Public Shared ReadOnly [Materiale] As String = "Materiale"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class RigaDichiarazioneEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("RigaDichiarazioneEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.RigaDichiarazioneEntity), GetType(RigaDichiarazioneEntity), GetType(RigaDichiarazioneEntityFactory), False)
				AddNavigatorMetaData(Of RigaDichiarazioneEntity, DichiarazioneEntity)("Dichiarazione", "RigheDettaglio", Sub(a, b) a._dichiarazione = b, Function(a) a._dichiarazione, Sub(a, b) a.Dichiarazione = b, DAL.RelationClasses.StaticRigaDichiarazioneRelations.DichiarazioneEntityUsingIdDichiarazioneStatic, Function() New RigaDichiarazioneRelations().DichiarazioneEntityUsingIdDichiarazione, Nothing, New Integer() { CInt(RigaDichiarazioneFieldIndex.IdDichiarazione) }, Nothing, True, CInt(DAL.EntityType.DichiarazioneEntity))
				AddNavigatorMetaData(Of RigaDichiarazioneEntity, MaterialeEntity)("Materiale", "RigheDichiarazioni", Sub(a, b) a._materiale = b, Function(a) a._materiale, Sub(a, b) a.Materiale = b, DAL.RelationClasses.StaticRigaDichiarazioneRelations.MaterialeEntityUsingIdMaterialeStatic, Function() New RigaDichiarazioneRelations().MaterialeEntityUsingIdMateriale, Nothing, New Integer() { CInt(RigaDichiarazioneFieldIndex.IdMateriale) }, Nothing, True, CInt(DAL.EntityType.MaterialeEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this RigaDichiarazioneEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for RigaDichiarazione which data should be fetched into this RigaDichiarazione object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for RigaDichiarazione which data should be fetched into this RigaDichiarazione object</param>
		''' <param name="validator">The custom validator object for this RigaDichiarazioneEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Dichiarazione' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoDichiarazione() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Dichiarazione")
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Materiale' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoMateriale() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Materiale")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this RigaDichiarazioneEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As RigaDichiarazioneRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Dichiarazione' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathDichiarazione() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Dichiarazione", CommonEntityBase.CreateEntityCollection(Of DichiarazioneEntity)())
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Materiale' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathMateriale() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Materiale", CommonEntityBase.CreateEntityCollection(Of MaterialeEntity)())
			End Get
		End Property

		''' <summary>The CodQuadro property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."CodQuadro".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [CodQuadro]() As System.String
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.CodQuadro), True), System.String)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.CodQuadro), value)
			End Set
		End Property

		''' <summary>The CodUnitaMisura property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."CodUnitaMisura".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CodUnitaMisura]() As System.String
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.CodUnitaMisura), True), System.String)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.CodUnitaMisura), value)
			End Set
		End Property

		''' <summary>The Descrizione property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The IdDichiarazione property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."IdDichiarazione".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [IdDichiarazione]() As System.Int32
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.IdDichiarazione), True), System.Int32)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.IdDichiarazione), value)
			End Set
		End Property

		''' <summary>The IdMateriale property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."IdMateriale".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [IdMateriale]() As System.Int32
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.IdMateriale), True), System.Int32)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.IdMateriale), value)
			End Set
		End Property

		''' <summary>The Iva property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."Iva".<br/>Table field type characteristics (type, precision, scale, length): Real, 24, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Iva]() As System.Single
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.Iva), True), System.Single)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.Iva), value)
			End Set
		End Property

		''' <summary>The PrezzoUnitario property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."PrezzoUnitario".<br/>Table field type characteristics (type, precision, scale, length): Money, 19, 4, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [PrezzoUnitario]() As System.Decimal
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.PrezzoUnitario), True), System.Decimal)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.PrezzoUnitario), value)
			End Set
		End Property

		''' <summary>The Procedura property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."Procedura".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Procedura]() As System.String
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.Procedura), True), System.String)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.Procedura), value)
			End Set
		End Property

		''' <summary>The Valore property of the Entity RigaDichiarazione<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RigaDichiarazione"."Valore".<br/>Table field type characteristics (type, precision, scale, length): Real, 24, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Valore]() As System.Single
			Get
				Return CType(GetValue(CInt(RigaDichiarazioneFieldIndex.Valore), True), System.Single)
			End Get
			Set
				SetValue(CInt(RigaDichiarazioneFieldIndex.Valore), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'DichiarazioneEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Dichiarazione]() As DichiarazioneEntity
			Get
				Return _dichiarazione
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Dichiarazione") 
			End Set
		End Property

		''' <summary>Gets / sets related entity of type 'MaterialeEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Materiale]() As MaterialeEntity
			Get
				Return _materiale
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Materiale") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: RigaDichiarazione.</summary>
	Public Enum RigaDichiarazioneFieldIndex
		[CodQuadro]
		[CodUnitaMisura]
		[Descrizione]
		[Id]
		[IdDichiarazione]
		[IdMateriale]
		[Iva]
		[PrezzoUnitario]
		[Procedura]
		[Valore]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: RigaDichiarazione.</summary>
	Public Class RigaDichiarazioneRelations



		''' <summary>Returns a new IEntityRelation Object, between RigaDichiarazioneEntity and DichiarazioneEntity over the m:1 relation they have, using the relation between the fields:
		''' RigaDichiarazione.IdDichiarazione - Dichiarazione.Id
		''' </summary>
		Public Overridable  ReadOnly Property DichiarazioneEntityUsingIdDichiarazione() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Dichiarazione", false, { DichiarazioneFields.Id, RigaDichiarazioneFields.IdDichiarazione })
			End Get
		End Property

		''' <summary>Returns a new IEntityRelation Object, between RigaDichiarazioneEntity and MaterialeEntity over the m:1 relation they have, using the relation between the fields:
		''' RigaDichiarazione.IdMateriale - Materiale.Id
		''' </summary>
		Public Overridable  ReadOnly Property MaterialeEntityUsingIdMateriale() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Materiale", false, { MaterialeFields.Id, RigaDichiarazioneFields.IdMateriale })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticRigaDichiarazioneRelations
		Friend Shared ReadOnly DichiarazioneEntityUsingIdDichiarazioneStatic As IEntityRelation = New RigaDichiarazioneRelations().DichiarazioneEntityUsingIdDichiarazione
		Friend Shared ReadOnly MaterialeEntityUsingIdMaterialeStatic As IEntityRelation = New RigaDichiarazioneRelations().MaterialeEntityUsingIdMateriale

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
