' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'RuoloUtente'.<br/><br/></summary>
	<Serializable()> _
	Public Class RuoloUtenteEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _utente As UtenteEntity

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New RuoloUtenteEntityStaticMetaData()
		Private Shared _relationsFactory As New RuoloUtenteRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Utente</summary>
			Public Shared ReadOnly [Utente] As String = "Utente"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class RuoloUtenteEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("RuoloUtenteEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.RuoloUtenteEntity), GetType(RuoloUtenteEntity), GetType(RuoloUtenteEntityFactory), False)
				AddNavigatorMetaData(Of RuoloUtenteEntity, UtenteEntity)("Utente", "Ruoli", Sub(a, b) a._utente = b, Function(a) a._utente, Sub(a, b) a.Utente = b, DAL.RelationClasses.StaticRuoloUtenteRelations.UtenteEntityUsingUserNameStatic, Function() New RuoloUtenteRelations().UtenteEntityUsingUserName, Nothing, New Integer() { CInt(RuoloUtenteFieldIndex.UserName) }, Nothing, True, CInt(DAL.EntityType.UtenteEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this RuoloUtenteEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="codRuolo">PK value for RuoloUtente which data should be fetched into this RuoloUtente object</param>
		''' <param name="userName">PK value for RuoloUtente which data should be fetched into this RuoloUtente object</param>
		Public Sub New(codRuolo As System.String, userName As System.String)
			Me.New(codRuolo, userName, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="codRuolo">PK value for RuoloUtente which data should be fetched into this RuoloUtente object</param>
		''' <param name="userName">PK value for RuoloUtente which data should be fetched into this RuoloUtente object</param>
		''' <param name="validator">The custom validator object for this RuoloUtenteEntity</param>
		Public Sub New(codRuolo As System.String, userName As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.CodRuolo = codRuolo
			Me.UserName = userName
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Utente' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoUtente() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Utente")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this RuoloUtenteEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As RuoloUtenteRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Utente' for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathUtente() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Utente", CommonEntityBase.CreateEntityCollection(Of UtenteEntity)())
			End Get
		End Property

		''' <summary>The CodRuolo property of the Entity RuoloUtente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RuoloUtente"."CodRuolo".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [CodRuolo]() As System.String
			Get
				Return CType(GetValue(CInt(RuoloUtenteFieldIndex.CodRuolo), True), System.String)
			End Get
			Set
				SetValue(CInt(RuoloUtenteFieldIndex.CodRuolo), value)
			End Set
		End Property

		''' <summary>The UserName property of the Entity RuoloUtente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "RuoloUtente"."UserName".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [UserName]() As System.String
			Get
				Return CType(GetValue(CInt(RuoloUtenteFieldIndex.UserName), True), System.String)
			End Get
			Set
				SetValue(CInt(RuoloUtenteFieldIndex.UserName), value)
			End Set
		End Property



		''' <summary>Gets / sets related entity of type 'UtenteEntity' which has to be set Imports a fetch action earlier. If no related entity is set for this property, null is returned.
		''' This property is not visible in databound grids.<br/><br/>
		''' </summary>
		<Browsable(False)> _
		Public Overridable Property [Utente]() As UtenteEntity
			Get
				Return _utente
			End Get
			Set
				SetSingleRelatedEntityNavigator(value, "Utente") 
			End Set
		End Property


		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: RuoloUtente.</summary>
	Public Enum RuoloUtenteFieldIndex
		[CodRuolo]
		[UserName]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: RuoloUtente.</summary>
	Public Class RuoloUtenteRelations



		''' <summary>Returns a new IEntityRelation Object, between RuoloUtenteEntity and UtenteEntity over the m:1 relation they have, using the relation between the fields:
		''' RuoloUtente.UserName - Utente.UserName
		''' </summary>
		Public Overridable  ReadOnly Property UtenteEntityUsingUserName() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Utente", false, { UtenteFields.UserName, RuoloUtenteFields.UserName })
			End Get
		End Property

	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticRuoloUtenteRelations
		Friend Shared ReadOnly UtenteEntityUsingUserNameStatic As IEntityRelation = New RuoloUtenteRelations().UtenteEntityUsingUserName

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
