' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Scadenza'.<br/><br/></summary>
	<Serializable()> _
	Public Class ScadenzaEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _dichiaraziones As EntityCollection(Of DichiarazioneEntity)

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New ScadenzaEntityStaticMetaData()
		Private Shared _relationsFactory As New ScadenzaRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Dichiaraziones</summary>
			Public Shared ReadOnly [Dichiaraziones] As String  = "Dichiaraziones"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class ScadenzaEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("ScadenzaEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.ScadenzaEntity), GetType(ScadenzaEntity), GetType(ScadenzaEntityFactory), False)
				AddNavigatorMetaData(Of ScadenzaEntity, EntityCollection(Of DichiarazioneEntity))("Dichiaraziones", Function(a) a._dichiaraziones, Sub(a, b) a._dichiaraziones = b, Function(a) a.Dichiaraziones, Function() New ScadenzaRelations().DichiarazioneEntityUsingIdScadenza, GetType(DichiarazioneEntity), CInt(DAL.EntityType.DichiarazioneEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this ScadenzaEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="id">PK value for Scadenza which data should be fetched into this Scadenza object</param>
		Public Sub New(id As System.Int32)
			Me.New(id, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="id">PK value for Scadenza which data should be fetched into this Scadenza object</param>
		''' <param name="validator">The custom validator object for this ScadenzaEntity</param>
		Public Sub New(id As System.Int32, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Id = id
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields:
		''' Codice .</summary>
		''' <returns>true if succeeded and the contents is read, false otherwise</returns>
		Public Function ConstructFilterForUCCodice() As IPredicateExpression
			Dim filter As New PredicateExpression()
			filter.Add(DAL.HelperClasses.ScadenzaFields.Codice = Me.Fields.GetCurrentValue(CInt(ScadenzaFieldIndex.Codice)))
 			Return filter
		End Function

		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Dichiarazione' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoDichiaraziones() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Dichiaraziones")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this ScadenzaEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As ScadenzaRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Dichiarazione'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathDichiaraziones() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Dichiaraziones", CommonEntityBase.CreateEntityCollection(Of DichiarazioneEntity)())
			End Get
		End Property

		''' <summary>The Anno property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."Anno".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Anno]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.Anno), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.Anno), value)
			End Set
		End Property

		''' <summary>The ApplicaInteressi property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."ApplicaInteressi".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [ApplicaInteressi]() As System.Boolean
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.ApplicaInteressi), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.ApplicaInteressi), value)
			End Set
		End Property

		''' <summary>The CodCategoria property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."CodCategoria".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [CodCategoria]() As System.String
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.CodCategoria), True), System.String)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.CodCategoria), value)
			End Set
		End Property

		''' <summary>The Codice property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."Codice".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [Codice]() As System.String
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.Codice), True), System.String)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.Codice), value)
			End Set
		End Property

		''' <summary>The CreaAutomatico property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."CreaAutomatico".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [CreaAutomatico]() As System.Boolean
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.CreaAutomatico), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.CreaAutomatico), value)
			End Set
		End Property

		''' <summary>The DataFine property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."DataFine".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [DataFine]() As System.DateTime
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.DataFine), True), System.DateTime)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.DataFine), value)
			End Set
		End Property

		''' <summary>The DataInizio property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."DataInizio".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [DataInizio]() As System.DateTime
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.DataInizio), True), System.DateTime)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.DataInizio), value)
			End Set
		End Property

		''' <summary>The DataScadenzaDichiarazione property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."DataScadenzaDichiarazione".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [DataScadenzaDichiarazione]() As System.DateTime
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.DataScadenzaDichiarazione), True), System.DateTime)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.DataScadenzaDichiarazione), value)
			End Set
		End Property

		''' <summary>The DataScadenzaPagamento property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."DataScadenzaPagamento".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [DataScadenzaPagamento]() As System.DateTime
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.DataScadenzaPagamento), True), System.DateTime)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.DataScadenzaPagamento), value)
			End Set
		End Property

		''' <summary>The Id property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, True</remarks>
		Public Overridable Property [Id]() As System.Int32
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.Id), True), System.Int32)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.Id), value)
			End Set
		End Property

		''' <summary>The RifPeriodo property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."RifPeriodo".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [RifPeriodo]() As System.String
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.RifPeriodo), True), System.String)
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.RifPeriodo), value)
			End Set
		End Property

		''' <summary>The TassoInteresse property of the Entity Scadenza<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Scadenza"."TassoInteresse".<br/>Table field type characteristics (type, precision, scale, length): Real, 24, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [TassoInteresse]() As Nullable(Of System.Single)
			Get
				Return CType(GetValue(CInt(ScadenzaFieldIndex.TassoInteresse), False), Nullable(Of System.Single))
			End Get
			Set
				SetValue(CInt(ScadenzaFieldIndex.TassoInteresse), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'DichiarazioneEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(DichiarazioneEntity))> _
		Public Overridable ReadOnly Property [Dichiaraziones]() As EntityCollection(Of DichiarazioneEntity)
			Get
				Return GetOrCreateEntityCollection(Of DichiarazioneEntity, DichiarazioneEntityFactory)("Scadenza", true, false, _dichiaraziones)
			End Get
		End Property




		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Scadenza.</summary>
	Public Enum ScadenzaFieldIndex
		[Anno]
		[ApplicaInteressi]
		[CodCategoria]
		[Codice]
		[CreaAutomatico]
		[DataFine]
		[DataInizio]
		[DataScadenzaDichiarazione]
		[DataScadenzaPagamento]
		[Id]
		[RifPeriodo]
		[TassoInteresse]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Scadenza.</summary>
	Public Class ScadenzaRelations

		''' <summary>Returns a new IEntityRelation Object, between ScadenzaEntity and DichiarazioneEntity over the 1:n relation they have, using the relation between the fields:
		''' Scadenza.Id - Dichiarazione.IdScadenza
		''' </summary>
		Public Overridable ReadOnly Property DichiarazioneEntityUsingIdScadenza() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Dichiaraziones", True, { ScadenzaFields.Id, DichiarazioneFields.IdScadenza })
			End Get				
		End Property


	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticScadenzaRelations
		Friend Shared ReadOnly DichiarazioneEntityUsingIdScadenzaStatic As IEntityRelation = New ScadenzaRelations().DichiarazioneEntityUsingIdScadenza

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
