' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'TipoMateriale'.<br/><br/></summary>
	<Serializable()> _
	Public Class TipoMaterialeEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _materiales As EntityCollection(Of MaterialeEntity)

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New TipoMaterialeEntityStaticMetaData()
		Private Shared _relationsFactory As New TipoMaterialeRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Materiales</summary>
			Public Shared ReadOnly [Materiales] As String  = "Materiales"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class TipoMaterialeEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("TipoMaterialeEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.TipoMaterialeEntity), GetType(TipoMaterialeEntity), GetType(TipoMaterialeEntityFactory), False)
				AddNavigatorMetaData(Of TipoMaterialeEntity, EntityCollection(Of MaterialeEntity))("Materiales", Function(a) a._materiales, Sub(a, b) a._materiales = b, Function(a) a.Materiales, Function() New TipoMaterialeRelations().MaterialeEntityUsingCodTipo, GetType(MaterialeEntity), CInt(DAL.EntityType.MaterialeEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this TipoMaterialeEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="codice">PK value for TipoMateriale which data should be fetched into this TipoMateriale object</param>
		Public Sub New(codice As System.String)
			Me.New(codice, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="codice">PK value for TipoMateriale which data should be fetched into this TipoMateriale object</param>
		''' <param name="validator">The custom validator object for this TipoMaterialeEntity</param>
		Public Sub New(codice As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.Codice = codice
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Materiale' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoMateriales() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Materiales")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this TipoMaterialeEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As TipoMaterialeRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Materiale'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathMateriales() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Materiales", CommonEntityBase.CreateEntityCollection(Of MaterialeEntity)())
			End Get
		End Property

		''' <summary>The Codice property of the Entity TipoMateriale<br/><br/></summary>
		''' <remarks> Mapped on  table field: "TipoMateriale"."Codice".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [Codice]() As System.String
			Get
				Return CType(GetValue(CInt(TipoMaterialeFieldIndex.Codice), True), System.String)
			End Get
			Set
				SetValue(CInt(TipoMaterialeFieldIndex.Codice), value)
			End Set
		End Property

		''' <summary>The Descrizione property of the Entity TipoMateriale<br/><br/></summary>
		''' <remarks> Mapped on  table field: "TipoMateriale"."Descrizione".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Descrizione]() As System.String
			Get
				Return CType(GetValue(CInt(TipoMaterialeFieldIndex.Descrizione), True), System.String)
			End Get
			Set
				SetValue(CInt(TipoMaterialeFieldIndex.Descrizione), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'MaterialeEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(MaterialeEntity))> _
		Public Overridable ReadOnly Property [Materiales]() As EntityCollection(Of MaterialeEntity)
			Get
				Return GetOrCreateEntityCollection(Of MaterialeEntity, MaterialeEntityFactory)("TipoMateriale", true, false, _materiales)
			End Get
		End Property




		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: TipoMateriale.</summary>
	Public Enum TipoMaterialeFieldIndex
		[Codice]
		[Descrizione]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: TipoMateriale.</summary>
	Public Class TipoMaterialeRelations

		''' <summary>Returns a new IEntityRelation Object, between TipoMaterialeEntity and MaterialeEntity over the 1:n relation they have, using the relation between the fields:
		''' TipoMateriale.Codice - Materiale.CodTipo
		''' </summary>
		Public Overridable ReadOnly Property MaterialeEntityUsingCodTipo() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Materiales", True, { TipoMaterialeFields.Codice, MaterialeFields.CodTipo })
			End Get				
		End Property


	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticTipoMaterialeRelations
		Friend Shared ReadOnly MaterialeEntityUsingCodTipoStatic As IEntityRelation = New TipoMaterialeRelations().MaterialeEntityUsingCodTipo

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
