' //////////////////////////////////////////////////////////////
' // <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
' //////////////////////////////////////////////////////////////
' // Code is generated on: 
' // Code is generated using templates: SD.TemplateBindings.SharedTemplates
' // Templates vendor: Solutions Design.
' //////////////////////////////////////////////////////////////
Imports System
Imports System.ComponentModel
Imports System.Collections.Generic
Imports System.Runtime.Serialization
Imports System.Xml.Serialization
Imports DAL
Imports DAL.HelperClasses
Imports DAL.FactoryClasses
Imports DAL.RelationClasses

Imports SD.LLBLGen.Pro.ORMSupportClasses

' __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
' __LLBLGENPRO_USER_CODE_REGION_END
Namespace DAL.EntityClasses

	''' <summary>Entity class which represents the entity 'Utente'.<br/><br/></summary>
	<Serializable()> _
	Public Class UtenteEntity 
		Inherits CommonEntityBase

		' __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		' __LLBLGENPRO_USER_CODE_REGION_END	
		Private _ruoli As EntityCollection(Of RuoloUtenteEntity)

		' __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		' __LLBLGENPRO_USER_CODE_REGION_END
		Private Shared _staticMetaData As New UtenteEntityStaticMetaData()
		Private Shared _relationsFactory As New UtenteRelations()
		
		''' <summary>All names of fields mapped onto a relation. Usable For In-memory filtering</summary>
		Public NotInheritable Class MemberNames
			Private Sub New()
			End Sub
			''' <summary>Member name Ruoli</summary>
			Public Shared ReadOnly [Ruoli] As String  = "Ruoli"

		End Class

		''' <summary>Static meta-data storage for navigator related information</summary>
		Protected Class UtenteEntityStaticMetaData 
			Inherits EntityStaticMetaDataBase
			
			Public Sub New()
				SetEntityCoreInfo("UtenteEntity", InheritanceHierarchyType.None, false, CInt(DAL.EntityType.UtenteEntity), GetType(UtenteEntity), GetType(UtenteEntityFactory), False)
				AddNavigatorMetaData(Of UtenteEntity, EntityCollection(Of RuoloUtenteEntity))("Ruoli", Function(a) a._ruoli, Sub(a, b) a._ruoli = b, Function(a) a.Ruoli, Function() New UtenteRelations().RuoloUtenteEntityUsingUserName, GetType(RuoloUtenteEntity), CInt(DAL.EntityType.RuoloUtenteEntity))
			End Sub
		End Class

		''' <summary>Static CTor</summary>
		Shared Sub New()

		End Sub
		
		''' <summary>CTor</summary>
		Public Sub New()
			MyBase.New()
			InitClassEmpty(Nothing, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="fields">Fields object to set as the fields for this entity.</param>
		Public Sub New(fields As IEntityFields2)
			MyBase.New()
			InitClassEmpty(Nothing, fields)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="validator">The custom validator object for this UtenteEntity</param>
		Public Sub New(validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
		End Sub
				
		''' <summary>CTor</summary>
		''' <param name="userName">PK value for Utente which data should be fetched into this Utente object</param>
		Public Sub New(userName As System.String)
			Me.New(userName, Nothing)
		End Sub

		''' <summary>CTor</summary>
		''' <param name="userName">PK value for Utente which data should be fetched into this Utente object</param>
		''' <param name="validator">The custom validator object for this UtenteEntity</param>
		Public Sub New(userName As System.String, validator As IValidator)
			MyBase.New()
			InitClassEmpty(validator, Nothing)
			Me.UserName = userName
		End Sub

		''' <summary>Private CTor for deserialization</summary>
		''' <param name="info"></param>
		''' <param name="context"></param>
		Protected Sub New(info As SerializationInfo, context As StreamingContext)
			MyBase.New(info, context)
			' __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			' __LLBLGENPRO_USER_CODE_REGION_END
		End Sub


		''' <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'RuoloUtente' to this entity.</summary>
		''' <returns></returns>
		Public Overridable Function GetRelationInfoRuoli() As IRelationPredicateBucket
			Return CreateRelationInfoForNavigator("Ruoli")
		End Function

		''' <summary>Gets the entity static meta data instance from the generated type.</summary>
		''' <returns>The instance requested</returns>
		Protected Overrides Function GetEntityStaticMetaData() As EntityStaticMetaDataBase 
			Return _staticMetaData
		End Function
		
		''' <summary>Initializes the class members</summary>
		Private Sub InitClassMembers()
			PerformDependencyInjection()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			' __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete()
		End Sub

		''' <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		''' <param name="validator">The validator object for this UtenteEntity</param>
		''' <param name="fields">Fields of this entity</param>
		Private Sub InitClassEmpty(validator As IValidator, fields As IEntityFields2)
			OnInitializing()
			If fields Is Nothing Then
				Me.Fields = CreateFields()
			Else
				Me.Fields = fields
			End If
			Me.Validator = validator
			InitClassMembers()

			' __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			' __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized()
		End Sub

		''' <summary>The relations Object holding all relations of this entity with other entity classes.</summary>
		Public  Shared ReadOnly Property Relations() As UtenteRelations
			Get	
				Return _relationsFactory
			End Get
		End Property

		''' <summary>Creates a New PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'RuoloUtente'  for this entity.</summary>
		''' <Returns>Ready to use IPrefetchPathElement2 implementation.</Returns>
		Public Shared ReadOnly Property PrefetchPathRuoli() As IPrefetchPathElement2
			Get
				Return _staticMetaData.GetPrefetchPathElement("Ruoli", CommonEntityBase.CreateEntityCollection(Of RuoloUtenteEntity)())
			End Get
		End Property

		''' <summary>The ArxivarPassword property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."ArxivarPassword".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [ArxivarPassword]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.ArxivarPassword), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.ArxivarPassword), value)
			End Set
		End Property

		''' <summary>The ArxivarUserId property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."ArxivarUserId".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [ArxivarUserId]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.ArxivarUserId), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.ArxivarUserId), value)
			End Set
		End Property

		''' <summary>The Cellulare property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."Cellulare".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Cellulare]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.Cellulare), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.Cellulare), value)
			End Set
		End Property

		''' <summary>The CompanyKey property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."CompanyKey".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [CompanyKey]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.CompanyKey), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.CompanyKey), value)
			End Set
		End Property

		''' <summary>The DataAccesso property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."DataAccesso".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataAccesso]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.DataAccesso), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.DataAccesso), value)
			End Set
		End Property

		''' <summary>The DataRegistrazione property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."DataRegistrazione".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataRegistrazione]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.DataRegistrazione), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.DataRegistrazione), value)
			End Set
		End Property

		''' <summary>The DataRilascioPassword property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."DataRilascioPassword".<br/>Table field type characteristics (type, precision, scale, length): SmallDateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [DataRilascioPassword]() As Nullable(Of System.DateTime)
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.DataRilascioPassword), False), Nullable(Of System.DateTime))
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.DataRilascioPassword), value)
			End Set
		End Property

		''' <summary>The Email property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."Email".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Email]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.Email), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.Email), value)
			End Set
		End Property

		''' <summary>The IsAttivo property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."IsAttivo".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, False, False</remarks>
		Public Overridable Property [IsAttivo]() As System.Boolean
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.IsAttivo), True), System.Boolean)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.IsAttivo), value)
			End Set
		End Property

		''' <summary>The Nome property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."Nome".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Nome]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.Nome), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.Nome), value)
			End Set
		End Property

		''' <summary>The Note property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."Note".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Note]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.Note), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.Note), value)
			End Set
		End Property

		''' <summary>The NumeroAccessi property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."NumeroAccessi".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [NumeroAccessi]() As Nullable(Of System.Int32)
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.NumeroAccessi), False), Nullable(Of System.Int32))
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.NumeroAccessi), value)
			End Set
		End Property

		''' <summary>The Password property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."Password".<br/>Table field type characteristics (type, precision, scale, length): Binary, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Password]() As System.Byte()
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.Password), True), System.Byte())
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.Password), value)
			End Set
		End Property

		''' <summary>The PasswordProvvisoria property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."PasswordProvvisoria".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [PasswordProvvisoria]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.PasswordProvvisoria), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.PasswordProvvisoria), value)
			End Set
		End Property

		''' <summary>The Telefono property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."Telefono".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): True, False, False</remarks>
		Public Overridable Property [Telefono]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.Telefono), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.Telefono), value)
			End Set
		End Property

		''' <summary>The UserName property of the Entity Utente<br/><br/></summary>
		''' <remarks> Mapped on  table field: "Utente"."UserName".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): False, True, False</remarks>
		Public Overridable Property [UserName]() As System.String
			Get
				Return CType(GetValue(CInt(UtenteFieldIndex.UserName), True), System.String)
			End Get
			Set
				SetValue(CInt(UtenteFieldIndex.UserName), value)
			End Set
		End Property

		''' <summary>Gets the EntityCollection with the related entities of type 'RuoloUtenteEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/>
		''' </summary>
		<TypeContainedAttribute(GetType(RuoloUtenteEntity))> _
		Public Overridable ReadOnly Property [Ruoli]() As EntityCollection(Of RuoloUtenteEntity)
			Get
				Return GetOrCreateEntityCollection(Of RuoloUtenteEntity, RuoloUtenteEntityFactory)("Utente", true, false, _ruoli)
			End Get
		End Property




		' __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		' __LLBLGENPRO_USER_CODE_REGION_END

	End Class
End Namespace

Namespace DAL
	''' <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Utente.</summary>
	Public Enum UtenteFieldIndex
		[ArxivarPassword]
		[ArxivarUserId]
		[Cellulare]
		[CompanyKey]
		[DataAccesso]
		[DataRegistrazione]
		[DataRilascioPassword]
		[Email]
		[IsAttivo]
		[Nome]
		[Note]
		[NumeroAccessi]
		[Password]
		[PasswordProvvisoria]
		[Telefono]
		[UserName]
		AmountOfFields
	End Enum
End Namespace

Namespace DAL.RelationClasses
	''' <summary>Implements the Shared Relations variant for the entity: Utente.</summary>
	Public Class UtenteRelations

		''' <summary>Returns a new IEntityRelation Object, between UtenteEntity and RuoloUtenteEntity over the 1:n relation they have, using the relation between the fields:
		''' Utente.UserName - RuoloUtente.UserName
		''' </summary>
		Public Overridable ReadOnly Property RuoloUtenteEntityUsingUserName() As IEntityRelation
			Get
				Return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Ruoli", True, { UtenteFields.UserName, RuoloUtenteFields.UserName })
			End Get				
		End Property


	End Class
		
	''' <summary>Static Class which Is used For providing relationship instances which are re-used internally For syncing</summary>
	Friend Class StaticUtenteRelations
		Friend Shared ReadOnly RuoloUtenteEntityUsingUserNameStatic As IEntityRelation = New UtenteRelations().RuoloUtenteEntityUsingUserName

		''' <summary>CTor</summary>
		Shared Sub New()
		End Sub
	End Class
End Namespace
