'//////////////////////////////////////////////////////////////
'// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
'//////////////////////////////////////////////////////////////
'// Code Is generated On: 
'// Code Is generated Using templates: SD.TemplateBindings.SharedTemplates
'// Templates vendor: Solutions Design.
'//////////////////////////////////////////////////////////////
Imports System
Imports System.Data
Imports System.Threading
Imports System.Threading.Tasks
Imports SD.LLBLGen.Pro.ORMSupportClasses

Namespace DAL.DatabaseSpecific
	''' <summary>Class which contains the Static logic To execute action stored procedures In the database.</summary>
	Public Class ActionProcedures
		''' <summary>private CTor so no instance can be created.</summary>
		Private Sub New()
		End Sub



		

	End Class
End Namespace
