'//////////////////////////////////////////////////////////////
'// <auto-generated>This code was generated by LLBLGen Pro 5.11.</auto-generated>
'//////////////////////////////////////////////////////////////
'// Code Is generated On: 
'// Code Is generated Using templates: SD.TemplateBindings.SharedTemplates
'// Templates vendor: Solutions Design.
'//////////////////////////////////////////////////////////////
Imports System
Imports System.Data
Imports System.Collections.Generic
Imports System.Threading
Imports System.Threading.Tasks
Imports SD.LLBLGen.Pro.ORMSupportClasses
Imports SD.LLBLGen.Pro.QuerySpec.Adapter

Namespace DAL.DatabaseSpecific
	''' <summary>Class which contains the Static logic To execute retrieval stored procedures In the database.</summary>
	Public Class RetrievalProcedures
		''' <summary>private CTor so no instance can be created.</summary>
		Private Sub New()
		End Sub
		



		''' <summary>Calls stored procedure 'getLibroSoci'.<br/><br/>
		''' </summary>
		''' <param name="dataAssemblea">Input parameter. </param>
		''' <returns>Filled DataTable With resultset(s) Of stored procedure</returns>
		Public Shared Function GetLibroSoci(dataAssemblea As System.DateTime) As DataTable
			Using dataAccessProvider As New DataAccessAdapter()
				Return GetLibroSoci(dataAssemblea, dataAccessProvider)
			End Using
		End Function

		''' <summary>Calls stored procedure 'getLibroSoci'.<br/><br/>
		''' </summary>
		''' <param name="dataAccessProvider">The data access provider.</param>
		''' <param name="dataAssemblea">Input parameter. </param>
		''' <returns>Filled DataTable With resultset(s) Of stored procedure</returns>
		Public Shared Function GetLibroSoci(dataAssemblea As System.DateTime, dataAccessProvider As IDataAccessCore) As DataTable
			Using spCall As StoredProcedureCall = CreateGetLibroSociCall(dataAccessProvider, dataAssemblea)
				Dim toReturn As DataTable = spCall.FillDataTable()
				Return toReturn
			End Using
		End Function

		''' <summary>Creates an IRetrievalQuery Object For a Call To the procedure 'getLibroSoci'.
		''' </summary>
		''' <param name="dataAssemblea">Input parameter Of stored procedure.</param>
		''' <returns>IRetrievalQuery Object which Is ready To use For datafetching</returns>
		Public Shared Function GetGetLibroSociCallAsQuery(dataAssemblea As System.DateTime) As IRetrievalQuery
			Using dataAccessProvider As New DataAccessAdapter()
				Return GetGetLibroSociCallAsQuery(dataAssemblea, dataAccessProvider)
			End Using
		End Function

		''' <summary>Creates an IRetrievalQuery Object For a Call To the procedure 'getLibroSoci'.
		''' </summary>
		''' <param name="dataAssemblea">Input parameter Of stored procedure.</param>
		''' <param name="dataAccessProvider">The data access provider.</param>
		''' <returns>IRetrievalQuery Object which Is ready To use For datafetching</returns>
		Public Shared Function GetGetLibroSociCallAsQuery(dataAssemblea As System.DateTime, dataAccessProvider As IDataAccessCore) As IRetrievalQuery
			Return CreateGetLibroSociCall(dataAccessProvider, dataAssemblea).ToRetrievalQuery()
		End Function


		''' <summary>Creates the Call Object For the Call 'GetLibroSoci' to stored procedure 'getLibroSoci'.</summary>
		''' <param name="dataAccessProvider">The data access provider.</param>
		''' <param name="dataAssemblea">Input parameter</param>
		''' <returns>Ready To use StoredProcedureCall Object</returns>
		Private Shared Function CreateGetLibroSociCall(dataAccessProvider As IDataAccessCore, dataAssemblea As System.DateTime) As StoredProcedureCall
			Return New StoredProcedureCall(dataAccessProvider, "[SociPolieco].[dbo].[getLibroSoci]", "GetLibroSoci") _ 
							.AddParameter("@DataAssemblea", "SmallDateTime", 0, ParameterDirection.Input, True, 0, 0, dataAssemblea)
		End Function


	End Class
End Namespace
